//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class CADASTRO
    {
        public Nullable<long> SEQUENCIA { get; set; }
        public string COD_CIA { get; set; }
        public string DT_BASE { get; set; }
        public string COD_PESS { get; set; }
        public string TIPO_PES { get; set; }
        public string NOM_SUBSC { get; set; }
        public string CPF_CNPJ { get; set; }
        public string ENDERECO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string UF { get; set; }
        public string PAIS { get; set; }
        public string CEP { get; set; }
        public System.DateTime DT_CARGA { get; set; }
    }
}
