//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONT_SEG
    {
        public string COD_CIA { get; set; }
        public string DT_BASE { get; set; }
        public string NUM_PROC { get; set; }
        public string NUM_SIN { get; set; }
        public string NOME { get; set; }
        public string CPF_CNPJ_SGDO { get; set; }
        public string UF_REC { get; set; }
        public decimal VR_SIN { get; set; }
        public decimal VR_PROVCONT { get; set; }
        public decimal VR_EST { get; set; }
        public string DT_OPER { get; set; }
        public string CLAS_EST { get; set; }
        public string MOT_OPER { get; set; }
        public Nullable<int> CD_MOEDA { get; set; }
        public Nullable<int> CD_EVT { get; set; }
        public string CD_SISTEMA { get; set; }
        public Nullable<decimal> VR_RES_CED { get; set; }
        public string CD_RESSEGURADOR { get; set; }
        public Nullable<int> NUM_SEQ { get; set; }
    }
}
