//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORRETAG
    {
        public Nullable<double> SEQUENCIA { get; set; }
        public string COD_CIA { get; set; }
        public string DT_BASE { get; set; }
        public string COD_RAMO { get; set; }
        public string NUM_APOL { get; set; }
        public string NUM_EN { get; set; }
        public Nullable<double> PARCELA { get; set; }
        public Nullable<double> QTDE_PARC { get; set; }
        public Nullable<double> VR_PG_COR { get; set; }
        public string NOM_CORAG { get; set; }
        public string CPF_CNPJ_C { get; set; }
        public string COD_COR { get; set; }
        public Nullable<int> NUM_SEQ { get; set; }
        public Nullable<int> CD_EVT { get; set; }
        public string CD_STM { get; set; }
        public string CD_ORIGEM { get; set; }
        public Nullable<int> TP_COMISSAO { get; set; }
        public decimal VL_AGENCIAMENTO { get; set; }
        public string CD_RESSEGURADOR { get; set; }
        public string CD_CTR_RESSEGURO { get; set; }
        public Nullable<int> CD_EXTRATO { get; set; }
        public string CD_CORR { get; set; }
        public string NR_MES_REF { get; set; }
        public Nullable<decimal> VL_ROYALTIES { get; set; }
        public Nullable<decimal> VL_ASSESSORIA { get; set; }
        public Nullable<decimal> PRO_LAB { get; set; }
    }
}
