//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_BIPRODUCAO_ODSEntities1 : DbContext
    {
        public DB_BIPRODUCAO_ODSEntities1()
            : base("name=DB_BIPRODUCAO_ODSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CADASTRO> CADASTROes { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TB_ODS_AGENTECOBRADOR> TB_ODS_AGENTECOBRADOR { get; set; }
        public virtual DbSet<TB_ODS_AGRUPAMENTO> TB_ODS_AGRUPAMENTO { get; set; }
        public virtual DbSet<TB_ODS_ASSESSORIA> TB_ODS_ASSESSORIA { get; set; }
        public virtual DbSet<TB_ODS_ASSESSORIA_FAIXA> TB_ODS_ASSESSORIA_FAIXA { get; set; }
        public virtual DbSet<TB_ODS_ASSESSORIA_PRODUTO> TB_ODS_ASSESSORIA_PRODUTO { get; set; }
        public virtual DbSet<TB_ODS_AVISO_CREDITO> TB_ODS_AVISO_CREDITO { get; set; }
        public virtual DbSet<TB_ODS_AVISO_CREDITO_FOLLOWUP> TB_ODS_AVISO_CREDITO_FOLLOWUP { get; set; }
        public virtual DbSet<TB_ODS_CADASTRO_ERROS> TB_ODS_CADASTRO_ERROS { get; set; }
        public virtual DbSet<TB_ODS_CANAL> TB_ODS_CANAL { get; set; }
        public virtual DbSet<TB_ODS_CEP> TB_ODS_CEP { get; set; }
        public virtual DbSet<TB_ODS_CLASS_CORRETOR> TB_ODS_CLASS_CORRETOR { get; set; }
        public virtual DbSet<TB_ODS_CLOSING_RATIO> TB_ODS_CLOSING_RATIO { get; set; }
        public virtual DbSet<TB_ODS_COBERTURA> TB_ODS_COBERTURA { get; set; }
        public virtual DbSet<TB_ODS_COMISSAO_ANTECIPADA_DETALHES> TB_ODS_COMISSAO_ANTECIPADA_DETALHES { get; set; }
        public virtual DbSet<TB_ODS_CONTA_KVW> TB_ODS_CONTA_KVW { get; set; }
        public virtual DbSet<TB_ODS_CONTROLE_EMISSAO_ANTECIPADA> TB_ODS_CONTROLE_EMISSAO_ANTECIPADA { get; set; }
        public virtual DbSet<TB_ODS_CORRENTISTA> TB_ODS_CORRENTISTA { get; set; }
        public virtual DbSet<TB_ODS_CORRETOR> TB_ODS_CORRETOR { get; set; }
        public virtual DbSet<TB_ODS_CORRETOR_ASSESSORIA> TB_ODS_CORRETOR_ASSESSORIA { get; set; }
        public virtual DbSet<TB_ODS_COTACAO_AUTO> TB_ODS_COTACAO_AUTO { get; set; }
        public virtual DbSet<TB_ODS_COTACAO_AUTO_UNICIDADE> TB_ODS_COTACAO_AUTO_UNICIDADE { get; set; }
        public virtual DbSet<TB_ODS_COTACAO_RE> TB_ODS_COTACAO_RE { get; set; }
        public virtual DbSet<TB_ODS_COTACAO_SSC> TB_ODS_COTACAO_SSC { get; set; }
        public virtual DbSet<TB_ODS_CREDITOS_ANTECIPADOS> TB_ODS_CREDITOS_ANTECIPADOS { get; set; }
        public virtual DbSet<TB_ODS_CREDITOS_ANTECIPADOS_HISTORICO> TB_ODS_CREDITOS_ANTECIPADOS_HISTORICO { get; set; }
        public virtual DbSet<TB_ODS_DAC_CONTA_RATEIO> TB_ODS_DAC_CONTA_RATEIO { get; set; }
        public virtual DbSet<TB_ODS_DAC_PARAMETRO> TB_ODS_DAC_PARAMETRO { get; set; }
        public virtual DbSet<TB_ODS_DAC_RATEIO> TB_ODS_DAC_RATEIO { get; set; }
        public virtual DbSet<TB_ODS_DAC_RATEIO_EMISSAO> TB_ODS_DAC_RATEIO_EMISSAO { get; set; }
        public virtual DbSet<TB_ODS_DAF> TB_ODS_DAF { get; set; }
        public virtual DbSet<TB_ODS_DETALHE_CLOSING_RATIO> TB_ODS_DETALHE_CLOSING_RATIO { get; set; }
        public virtual DbSet<TB_ODS_DETALHE_PARCELA> TB_ODS_DETALHE_PARCELA { get; set; }
        public virtual DbSet<TB_ODS_DETALHE_PROPOSTA> TB_ODS_DETALHE_PROPOSTA { get; set; }
        public virtual DbSet<TB_ODS_DETALHE_SINISTRO> TB_ODS_DETALHE_SINISTRO { get; set; }
        public virtual DbSet<TB_ODS_DOMINIO> TB_ODS_DOMINIO { get; set; }
        public virtual DbSet<TB_ODS_EMISSAO> TB_ODS_EMISSAO { get; set; }
        public virtual DbSet<TB_ODS_EMISSAO_ANTERIOR> TB_ODS_EMISSAO_ANTERIOR { get; set; }
        public virtual DbSet<TB_ODS_ENQUADRAMENTO> TB_ODS_ENQUADRAMENTO { get; set; }
        public virtual DbSet<TB_ODS_ENTIDADE> TB_ODS_ENTIDADE { get; set; }
        public virtual DbSet<TB_ODS_EVENTO> TB_ODS_EVENTO { get; set; }
        public virtual DbSet<TB_ODS_EVENTOS_CONTABEIS> TB_ODS_EVENTOS_CONTABEIS { get; set; }
        public virtual DbSet<TB_ODS_EXECUTIVO> TB_ODS_EXECUTIVO { get; set; }
        public virtual DbSet<TB_ODS_EXTRATO_COMISSAO> TB_ODS_EXTRATO_COMISSAO { get; set; }
        public virtual DbSet<TB_ODS_F_COBRANCA> TB_ODS_F_COBRANCA { get; set; }
        public virtual DbSet<TB_ODS_F_COMISSAO> TB_ODS_F_COMISSAO { get; set; }
        public virtual DbSet<TB_ODS_F_EMISSAO> TB_ODS_F_EMISSAO { get; set; }
        public virtual DbSet<TB_ODS_F_ITEM_QUESTIONARIO> TB_ODS_F_ITEM_QUESTIONARIO { get; set; }
        public virtual DbSet<TB_ODS_F_SINISTRO> TB_ODS_F_SINISTRO { get; set; }
        public virtual DbSet<TB_ODS_FIPECAFI_PREMIO> TB_ODS_FIPECAFI_PREMIO { get; set; }
        public virtual DbSet<TB_ODS_FIPECAFI_SERVICO> TB_ODS_FIPECAFI_SERVICO { get; set; }
        public virtual DbSet<TB_ODS_FIPECAFI_SINISTRO> TB_ODS_FIPECAFI_SINISTRO { get; set; }
        public virtual DbSet<TB_ODS_FT_PPNG_SUN> TB_ODS_FT_PPNG_SUN { get; set; }
        public virtual DbSet<TB_ODS_FT_SUN> TB_ODS_FT_SUN { get; set; }
        public virtual DbSet<TB_ODS_HIERARQUIA> TB_ODS_HIERARQUIA { get; set; }
        public virtual DbSet<TB_ODS_ITEM> TB_ODS_ITEM { get; set; }
        public virtual DbSet<TB_ODS_ITEM_COBERTURA> TB_ODS_ITEM_COBERTURA { get; set; }
        public virtual DbSet<TB_ODS_ITEM_DETALHE> TB_ODS_ITEM_DETALHE { get; set; }
        public virtual DbSet<TB_ODS_ITEM_PPNG> TB_ODS_ITEM_PPNG { get; set; }
        public virtual DbSet<TB_ODS_ITEM_QUESTIONARIO> TB_ODS_ITEM_QUESTIONARIO { get; set; }
        public virtual DbSet<TB_ODS_JUDICIAL> TB_ODS_JUDICIAL { get; set; }
        public virtual DbSet<TB_ODS_LANCAMENTO_COMISSAO> TB_ODS_LANCAMENTO_COMISSAO { get; set; }
        public virtual DbSet<TB_ODS_LOG_GRAVA_DADOS> TB_ODS_LOG_GRAVA_DADOS { get; set; }
        public virtual DbSet<TB_ODS_MATRIZ> TB_ODS_MATRIZ { get; set; }
        public virtual DbSet<TB_ODS_MOEDA_REF> TB_ODS_MOEDA_REF { get; set; }
        public virtual DbSet<TB_ODS_NATUREZA> TB_ODS_NATUREZA { get; set; }
        public virtual DbSet<TB_ODS_OBJETO> TB_ODS_OBJETO { get; set; }
        public virtual DbSet<TB_ODS_OCORRENCIAS> TB_ODS_OCORRENCIAS { get; set; }
        public virtual DbSet<TB_ODS_OCORRENCIAS_OSCILACAO_CAMBIAL> TB_ODS_OCORRENCIAS_OSCILACAO_CAMBIAL { get; set; }
        public virtual DbSet<TB_ODS_OPERACIONAL> TB_ODS_OPERACIONAL { get; set; }
        public virtual DbSet<TB_ODS_PAGAMENTO_SINISTRO> TB_ODS_PAGAMENTO_SINISTRO { get; set; }
        public virtual DbSet<TB_ODS_PARAMETRO> TB_ODS_PARAMETRO { get; set; }
        public virtual DbSet<TB_ODS_PARAMETRO_ARQUIVO> TB_ODS_PARAMETRO_ARQUIVO { get; set; }
        public virtual DbSet<TB_ODS_PARCELA_COMISSAO_ITEM_COBERTURA> TB_ODS_PARCELA_COMISSAO_ITEM_COBERTURA { get; set; }
        public virtual DbSet<TB_ODS_PARTCORRETOR> TB_ODS_PARTCORRETOR { get; set; }
        public virtual DbSet<TB_ODS_PARTCOSSEGURO> TB_ODS_PARTCOSSEGURO { get; set; }
        public virtual DbSet<TB_ODS_PARTRESSEGURO> TB_ODS_PARTRESSEGURO { get; set; }
        public virtual DbSet<TB_ODS_PERFIL_COTACAO> TB_ODS_PERFIL_COTACAO { get; set; }
        public virtual DbSet<TB_ODS_PERFIL_COTACAO_RE> TB_ODS_PERFIL_COTACAO_RE { get; set; }
        public virtual DbSet<TB_ODS_PLANO_CONTAS> TB_ODS_PLANO_CONTAS { get; set; }
        public virtual DbSet<TB_ODS_PRODUTO> TB_ODS_PRODUTO { get; set; }
        public virtual DbSet<TB_ODS_PRODUTO_VERSAO> TB_ODS_PRODUTO_VERSAO { get; set; }
        public virtual DbSet<TB_ODS_PROPOSTA> TB_ODS_PROPOSTA { get; set; }
        public virtual DbSet<TB_ODS_RAMO> TB_ODS_RAMO { get; set; }
        public virtual DbSet<TB_ODS_RECEPCAO_AUXILIAR> TB_ODS_RECEPCAO_AUXILIAR { get; set; }
        public virtual DbSet<TB_ODS_REGIAO_CEP_UF> TB_ODS_REGIAO_CEP_UF { get; set; }
        public virtual DbSet<TB_ODS_REGIAO_CLOSING_RATIO> TB_ODS_REGIAO_CLOSING_RATIO { get; set; }
        public virtual DbSet<TB_ODS_REGIAO_COTACAO> TB_ODS_REGIAO_COTACAO { get; set; }
        public virtual DbSet<TB_ODS_REGIAO_COTACAO_RE> TB_ODS_REGIAO_COTACAO_RE { get; set; }
        public virtual DbSet<TB_ODS_REGIAO_PROPOSTA> TB_ODS_REGIAO_PROPOSTA { get; set; }
        public virtual DbSet<TB_ODS_REGIONAL> TB_ODS_REGIONAL { get; set; }
        public virtual DbSet<TB_ODS_RESSEGURADOR> TB_ODS_RESSEGURADOR { get; set; }
        public virtual DbSet<TB_ODS_RESSEGURO_COBERTURA> TB_ODS_RESSEGURO_COBERTURA { get; set; }
        public virtual DbSet<TB_ODS_RESSEGURO_EMISSAO_MANUAL> TB_ODS_RESSEGURO_EMISSAO_MANUAL { get; set; }
        public virtual DbSet<TB_ODS_RESSEGURO_GERAL> TB_ODS_RESSEGURO_GERAL { get; set; }
        public virtual DbSet<TB_ODS_RESSEGURO_PARAMETRO> TB_ODS_RESSEGURO_PARAMETRO { get; set; }
        public virtual DbSet<TB_ODS_RESSEGURO_SINISTRO> TB_ODS_RESSEGURO_SINISTRO { get; set; }
        public virtual DbSet<TB_ODS_REVENDA> TB_ODS_REVENDA { get; set; }
        public virtual DbSet<TB_ODS_REVENDA_COTACAO> TB_ODS_REVENDA_COTACAO { get; set; }
        public virtual DbSet<TB_ODS_RISCO_SINISTRO> TB_ODS_RISCO_SINISTRO { get; set; }
        public virtual DbSet<TB_ODS_SEGMENTO> TB_ODS_SEGMENTO { get; set; }
        public virtual DbSet<TB_ODS_SEGURADORA> TB_ODS_SEGURADORA { get; set; }
        public virtual DbSet<TB_ODS_SEQUENCIAL> TB_ODS_SEQUENCIAL { get; set; }
        public virtual DbSet<TB_ODS_SINISTRO> TB_ODS_SINISTRO { get; set; }
        public virtual DbSet<TB_ODS_SISTEMA> TB_ODS_SISTEMA { get; set; }
        public virtual DbSet<TB_ODS_SUB_REGIONAL> TB_ODS_SUB_REGIONAL { get; set; }
        public virtual DbSet<TB_ODS_SUCURSAL> TB_ODS_SUCURSAL { get; set; }
        public virtual DbSet<TB_ODS_SUN_HISTORICO> TB_ODS_SUN_HISTORICO { get; set; }
        public virtual DbSet<TB_ODS_SUN_LANCAMENTOS> TB_ODS_SUN_LANCAMENTOS { get; set; }
        public virtual DbSet<TB_ODS_TIPO_COBRANCA> TB_ODS_TIPO_COBRANCA { get; set; }
        public virtual DbSet<TB_ODS_TIPO_PAGAMENTO_SINISTRO> TB_ODS_TIPO_PAGAMENTO_SINISTRO { get; set; }
        public virtual DbSet<TB_ODS_TITULOS> TB_ODS_TITULOS { get; set; }
        public virtual DbSet<TB_ODS_TITULOS_RAMO_ITEM_COBERTURA> TB_ODS_TITULOS_RAMO_ITEM_COBERTURA { get; set; }
        public virtual DbSet<TB_ODS_VEICULO_COTACAO> TB_ODS_VEICULO_COTACAO { get; set; }
        public virtual DbSet<CONT_SEG> CONT_SEG { get; set; }
        public virtual DbSet<CORRETAG> CORRETAGs { get; set; }
        public virtual DbSet<PREMIT> PREMITs { get; set; }
        public virtual DbSet<RESCODIA> RESCODIAs { get; set; }
        public virtual DbSet<RESCOM> RESCOMs { get; set; }
        public virtual DbSet<SEEMIT> SEEMITs { get; set; }
        public virtual DbSet<TB_AUX_PREMIO_SELECIONADO_RATEIO_DAC> TB_AUX_PREMIO_SELECIONADO_RATEIO_DAC { get; set; }
        public virtual DbSet<TB_ODS_AJUSTES_EST> TB_ODS_AJUSTES_EST { get; set; }
        public virtual DbSet<TB_ODS_CONTROLE_DATA_ETL> TB_ODS_CONTROLE_DATA_ETL { get; set; }
        public virtual DbSet<TB_ODS_EVENTOSQUADROSFIP> TB_ODS_EVENTOSQUADROSFIP { get; set; }
        public virtual DbSet<TB_ODS_MOEDA> TB_ODS_MOEDA { get; set; }
        public virtual DbSet<TB_ODS_PLANO_CONTAS_HISTORICO> TB_ODS_PLANO_CONTAS_HISTORICO { get; set; }
        public virtual DbSet<TB_ODS_SEGURADO> TB_ODS_SEGURADO { get; set; }
        public virtual DbSet<TB_ODS_SUN_EVENTOS> TB_ODS_SUN_EVENTOS { get; set; }
    }
}
