//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREMIT
    {
        public Nullable<double> SEQUENCIA { get; set; }
        public string COD_CIA { get; set; }
        public string NUM_PROC { get; set; }
        public string DT_BASE { get; set; }
        public Nullable<double> TIPO_MOV { get; set; }
        public string UF_DEP { get; set; }
        public string UF_RISCO { get; set; }
        public string COD_RAMO { get; set; }
        public string NUM_APOL { get; set; }
        public string NUM_END { get; set; }
        public string NUM_PROP { get; set; }
        public string DT_PROP { get; set; }
        public string CPF_SEG { get; set; }
        public Nullable<double> QTD_SEG { get; set; }
        public string CPF_TOM { get; set; }
        public Nullable<double> QTD_TOM { get; set; }
        public string DT_EMIS { get; set; }
        public string DT_INI_VIG { get; set; }
        public string DT_FIM_VIG { get; set; }
        public Nullable<decimal> PR_EMIT { get; set; }
        public Nullable<decimal> PR_COS_CED { get; set; }
        public Nullable<decimal> AD_FRAC { get; set; }
        public Nullable<decimal> CUST_APOL { get; set; }
        public Nullable<decimal> IOF { get; set; }
        public Nullable<decimal> COMIS { get; set; }
        public Nullable<decimal> COMIS_COSS { get; set; }
        public Nullable<decimal> PRO_LAB { get; set; }
        public string CPF_ESTIP { get; set; }
        public Nullable<decimal> VL_IS { get; set; }
        public Nullable<decimal> PR_RES_CED { get; set; }
        public Nullable<decimal> COMIS_RESS { get; set; }
        public Nullable<int> NUM_SEQ { get; set; }
        public string CD_ORIGEM { get; set; }
        public Nullable<int> ID_APOLICE { get; set; }
        public Nullable<int> CD_MOEDA { get; set; }
        public Nullable<decimal> VAL_AGENC { get; set; }
        public string CD_STM { get; set; }
        public Nullable<int> CD_EVT { get; set; }
        public Nullable<int> CD_PARCELA { get; set; }
        public Nullable<decimal> COMIS_CUST { get; set; }
        public decimal VL_ROYALTIES { get; set; }
        public string CD_RESSEGURADOR { get; set; }
        public string CD_CTR_RESSEGURO { get; set; }
        public Nullable<decimal> VL_CUSTO_AQUISICAO { get; set; }
        public string DT_INICIO_VIG_OR { get; set; }
        public string DT_FIM_VIG_OR { get; set; }
        public string NM_SEGURADO { get; set; }
        public string CD_ENDOSSO { get; set; }
        public Nullable<decimal> VL_ASSESSORIA { get; set; }
        public Nullable<decimal> PC_ASSESSORIA { get; set; }
        public string CD_PRODUTO { get; set; }
        public string IN_UTILIZACAO_DAF { get; set; }
        public Nullable<decimal> VL_RATEIO_DAC { get; set; }
        public string TP_RENOVACAO { get; set; }
        public string CD_CORRETOR { get; set; }
        public Nullable<int> QT_PRESTACAO { get; set; }
    }
}
