//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESCODIA
    {
        public Nullable<double> SEQUENCIA { get; set; }
        public string COD_CIA { get; set; }
        public string DT_BASE { get; set; }
        public Nullable<double> TIPO_MOV { get; set; }
        public string COD_RAMO { get; set; }
        public string NUM_APOL { get; set; }
        public string NUM_END { get; set; }
        public string NUM_PROP { get; set; }
        public string DT_PROP { get; set; }
        public string DT_EMIS_AP { get; set; }
        public string DT_EMIS_EN { get; set; }
        public string DT_INI_VIG { get; set; }
        public string DT_FIM_VIG { get; set; }
        public Nullable<decimal> CO_EMIT { get; set; }
        public Nullable<decimal> COS_EMIT { get; set; }
        public Nullable<decimal> RES_EMIT { get; set; }
        public Nullable<decimal> CONGAN01 { get; set; }
        public Nullable<decimal> CONGAN02 { get; set; }
        public Nullable<decimal> CONGAN03 { get; set; }
        public Nullable<decimal> CONGAN04 { get; set; }
        public Nullable<decimal> CONGAN05 { get; set; }
        public Nullable<decimal> CONGAN06 { get; set; }
        public Nullable<decimal> CONGAN07 { get; set; }
        public Nullable<decimal> CONGAN08 { get; set; }
        public Nullable<decimal> CONGAN09 { get; set; }
        public Nullable<decimal> CONGAN10 { get; set; }
        public Nullable<decimal> CONGAN11 { get; set; }
        public Nullable<decimal> CONGAN12 { get; set; }
        public Nullable<decimal> CONGAN13 { get; set; }
        public Nullable<decimal> CONGAN14 { get; set; }
        public Nullable<decimal> CONGAN15 { get; set; }
        public Nullable<decimal> CONGAN16 { get; set; }
        public Nullable<decimal> CONGAN17 { get; set; }
        public Nullable<decimal> CONGAN18 { get; set; }
        public Nullable<decimal> CONGAN19 { get; set; }
        public Nullable<decimal> CONGAN20 { get; set; }
        public Nullable<decimal> CONGAN21 { get; set; }
        public Nullable<decimal> CONGAN22 { get; set; }
        public Nullable<decimal> CONGAN23 { get; set; }
        public Nullable<decimal> CONGAN24 { get; set; }
        public Nullable<decimal> CONGAN25 { get; set; }
        public Nullable<decimal> CONGAN26 { get; set; }
        public Nullable<decimal> CONGAN27 { get; set; }
        public Nullable<decimal> CONGAN28 { get; set; }
        public Nullable<decimal> CONGAN29 { get; set; }
        public Nullable<decimal> CONGAN30 { get; set; }
        public Nullable<decimal> CONGAN31 { get; set; }
        public Nullable<int> NUM_SEQ { get; set; }
        public Nullable<int> CD_EVT { get; set; }
        public string CD_ORIGEM { get; set; }
        public Nullable<int> CD_MOEDA { get; set; }
        public string COD_STM { get; set; }
        public decimal VL_AGENCIAMENTO { get; set; }
        public Nullable<System.DateTime> DT_CALCULO_RESERVA { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_FATO { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_SUN { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_RO { get; set; }
        public Nullable<double> VL_MOEDA { get; set; }
        public Nullable<decimal> VL_OSCILACAO_CAMBIAL_NG { get; set; }
        public Nullable<decimal> VL_OSCILACAO_CAMBIAL_COS_NG { get; set; }
        public Nullable<decimal> VL_OSCILACAO_CAMBIAL_RES_NG { get; set; }
        public Nullable<decimal> VL_OSCILACAO_CAMBIAL_AGENC_NG { get; set; }
        public string IN_CANCELAMENTO_PT { get; set; }
        public string CD_ENDOSSO { get; set; }
        public Nullable<decimal> VL_ASSESSORIA { get; set; }
        public Nullable<decimal> PC_ASSESSORIA { get; set; }
        public Nullable<decimal> VL_ROYALTIES { get; set; }
        public Nullable<decimal> PRO_LAB { get; set; }
        public Nullable<decimal> VL_RATEIO_DAC { get; set; }
        public string TP_RENOVACAO { get; set; }
    }
}
