//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESCOM
    {
        public Nullable<double> SEQUENCIA { get; set; }
        public string COD_CIA { get; set; }
        public string DT_BASE { get; set; }
        public Nullable<double> TIPO_MOV { get; set; }
        public string COD_RAMO { get; set; }
        public string NUM_APOL { get; set; }
        public string NUM_END { get; set; }
        public string NUM_PROP { get; set; }
        public string DT_PROP { get; set; }
        public string DT_EMIS_AP { get; set; }
        public string DT_EMIS_EN { get; set; }
        public string DT_INI_VIG { get; set; }
        public string DT_FIM_VIG { get; set; }
        public Nullable<decimal> CO_EMIT { get; set; }
        public Nullable<decimal> CO_N_GANHO { get; set; }
        public Nullable<decimal> CO_BRU_CO { get; set; }
        public Nullable<decimal> CO_COC_NG { get; set; }
        public Nullable<decimal> CO_BRU_RE { get; set; }
        public Nullable<decimal> CO_RES_NG { get; set; }
        public Nullable<int> NUM_SEQ { get; set; }
        public string CD_ORIGEM { get; set; }
        public Nullable<int> CD_MOEDA { get; set; }
        public string CD_STM { get; set; }
        public Nullable<int> CD_EVT { get; set; }
        public decimal VL_AGENCIAMENTO_NAO_GANHO { get; set; }
        public decimal VL_AGENCIAMENTO { get; set; }
        public Nullable<decimal> VL_OSCILACAO_CAMBIAL_NG { get; set; }
        public Nullable<decimal> VL_OSCILACAO_CAMBIAL_COS_NG { get; set; }
        public Nullable<decimal> VL_OSCILACAO_CAMBIAL_RES_NG { get; set; }
        public Nullable<decimal> VL_OSCILACAO_CAMBIAL_AGENC_NG { get; set; }
        public string IN_CANCELAMENTO_PT { get; set; }
        public string CD_ENDOSSO { get; set; }
        public Nullable<decimal> VL_ASSESSORIA { get; set; }
        public Nullable<decimal> VL_ASSESSORIA_NAO_GANHO { get; set; }
        public Nullable<decimal> PC_ASSESSORIA { get; set; }
        public Nullable<decimal> VL_ROYALTIES { get; set; }
        public Nullable<decimal> VL_ROYALTIES_NAO_GANHO { get; set; }
        public Nullable<decimal> PRO_LAB { get; set; }
        public Nullable<decimal> PRO_LAB_NAO_GANHO { get; set; }
        public Nullable<decimal> VL_RATEIO_DAC { get; set; }
        public Nullable<decimal> VL_RATEIO_DAC_NAO_GANHO { get; set; }
        public string TP_RENOVACAO { get; set; }
    }
}
