//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AUX_PREMIO_SELECIONADO_RATEIO_DAC
    {
        public string CD_APOLICE { get; set; }
        public string TP_ENDOSSO { get; set; }
        public string CD_ENDOSSO { get; set; }
        public string CD_ENDOSSO_CANCELADO { get; set; }
        public string CD_RAMO { get; set; }
        public double TIPO_MOV { get; set; }
        public int CD_EVT { get; set; }
        public string CD_PRODUTO { get; set; }
        public string IN_UTILIZACAO_DAF { get; set; }
        public decimal PR_EMIT { get; set; }
        public string TP_RENOVACAO { get; set; }
    }
}
