//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_EVENTOSQUADROSFIP
    {
        public string CD_QUADRO { get; set; }
        public string CD_SISTEMA { get; set; }
        public int CD_EVENTO { get; set; }
        public System.DateTime DT_INICIOVIG { get; set; }
        public System.DateTime DT_FINALVIG { get; set; }
        public string CD_TPMOID { get; set; }
        public string CD_CMPID { get; set; }
        public Nullable<bool> IN_SINAL { get; set; }
        public string CD_TPMOID2 { get; set; }
        public string CD_CMPID2 { get; set; }
        public Nullable<bool> IN_SINAL2 { get; set; }
        public Nullable<int> TP_VARIACAO { get; set; }
        public Nullable<int> TP_ENDOSSO { get; set; }
        public string CD_TIPO_RESSEGURADOR { get; set; }
    }
}
