//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_MOEDA
    {
        public Nullable<int> ID_MOEDA { get; set; }
        public int CD_MOEDA { get; set; }
        public System.DateTime DT_INIVIG { get; set; }
        public System.DateTime DT_FIMVIG { get; set; }
        public string DS_MOEDA { get; set; }
        public Nullable<decimal> VLR_MOEDA { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    
        public virtual TB_ODS_MOEDA_REF TB_ODS_MOEDA_REF { get; set; }
    }
}
