//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_PAGAMENTO_SINISTRO
    {
        public string CD_AVS_SGO { get; set; }
        public string CD_MOV { get; set; }
        public Nullable<System.DateTime> DT_PAGTO { get; set; }
        public Nullable<decimal> VL_PAGTO { get; set; }
        public string CD_BANCO { get; set; }
        public string CD_AGENCIA { get; set; }
        public string CD_CONTA { get; set; }
        public Nullable<int> CD_FRM_PAGAMENTO { get; set; }
        public string CD_BANCO_PAG { get; set; }
        public string CD_AGENCIA_PAG { get; set; }
        public string CD_CONTA_PAG { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public string CD_STM { get; set; }
        public string NR_CPF_CNPJ { get; set; }
        public string CD_TRANSACAO { get; set; }
        public Nullable<int> NR_PAGTO_EXTRATO { get; set; }
    }
}
