//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_RESSEGURADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ODS_RESSEGURADOR()
        {
            this.TB_ODS_RESSEGURO_EMISSAO_MANUAL = new HashSet<TB_ODS_RESSEGURO_EMISSAO_MANUAL>();
            this.TB_ODS_RESSEGURO_SINISTRO = new HashSet<TB_ODS_RESSEGURO_SINISTRO>();
        }
    
        public string CD_RESSEGURADOR { get; set; }
        public string DS_RESSEGURADOR { get; set; }
        public string CD_TIPO_RESSEGURADOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_RESSEGURO_EMISSAO_MANUAL> TB_ODS_RESSEGURO_EMISSAO_MANUAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_RESSEGURO_SINISTRO> TB_ODS_RESSEGURO_SINISTRO { get; set; }
    }
}
