//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_COBERTURA
    {
        public string CD_PROD { get; set; }
        public string CD_RAMO { get; set; }
        public string CD_COB { get; set; }
        public string TP_COBERTURA { get; set; }
        public System.DateTime DT_INICIO_VIGENCIA { get; set; }
        public string CD_SISTEMA { get; set; }
        public string DS_COBERTURA { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public Nullable<System.DateTime> DT_FIM_VIGENCIA { get; set; }
        public string IN_COB_OBSOLETA { get; set; }
        public string IN_PC_CORPORATE { get; set; }
        public string IN_LMG_AUTOMATICO { get; set; }
        public string CD_PROD_VERSAO { get; set; }
        public string CD_SUSEP { get; set; }
    }
}
