//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_RESSEGURO_COBERTURA
    {
        public int ID_RESSEGURO { get; set; }
        public string CD_COBERTURA { get; set; }
        public bool IN_COBERTURA_EXCLUDENTE { get; set; }
        public bool IN_CALCULA_LMI { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    }
}
