//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_F_COBRANCA
    {
        public string CD_LIDER { get; set; }
        public string NR_APOLICE_DW { get; set; }
        public string TP_ENDOSSO { get; set; }
        public string NR_ENDOSSO_DW { get; set; }
        public int CD_PARCELA { get; set; }
        public string CD_RAMO_SUSEP { get; set; }
        public int CD_ITEM { get; set; }
        public string CD_COBERTURA { get; set; }
        public string CD_CORRETOR { get; set; }
        public string CD_ORIGEM { get; set; }
        public string CD_SISTEMA { get; set; }
        public int CD_EVENTO { get; set; }
        public System.DateTime DT_OPERACAO { get; set; }
        public Nullable<System.DateTime> DT_PAGAMENTO { get; set; }
        public Nullable<System.DateTime> DT_BAIXA { get; set; }
        public string CD_AGENTE { get; set; }
        public string CD_BOLETO { get; set; }
        public string CD_DOCUMENTO { get; set; }
        public string CD_AGENCIA { get; set; }
        public string NR_CONTACORRENTE { get; set; }
        public string CD_NOSSO_NUMERO { get; set; }
        public decimal VL_EVENTO { get; set; }
        public decimal VL_ADICIONAL_FRAC { get; set; }
        public decimal VL_CUSTO_APOLIC { get; set; }
        public decimal VL_IOF { get; set; }
        public string CD_MOEDA { get; set; }
        public long ID_SEQUENCIA { get; set; }
        public System.DateTime DT_CARGA { get; set; }
        public Nullable<System.DateTime> DT_PROCESSAMENTO { get; set; }
        public string NM_ARQUIVO { get; set; }
        public string DS_OBSERVACAO { get; set; }
        public decimal VL_COMISSAO { get; set; }
        public decimal VL_CUSTO_COMISSAO { get; set; }
    }
}
