//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_EMISSAO_ANTERIOR
    {
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public int CD_ITEM { get; set; }
        public string NR_APO_ANT { get; set; }
        public string NR_END_ANT { get; set; }
        public string CD_LIDER { get; set; }
        public string CD_ORIGEM { get; set; }
        public string TP_ENDOSSO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public string CD_CI_RENOV { get; set; }
        public string CD_SUC_RENOVA { get; set; }
        public string CD_ITEM_RENOVA { get; set; }
    
        public virtual TB_ODS_ITEM TB_ODS_ITEM { get; set; }
    }
}
