//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_LANCAMENTO_COMISSAO
    {
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public string CD_CORR { get; set; }
        public Nullable<int> CD_PARCELA { get; set; }
        public string CD_RAMO { get; set; }
        public string NR_MES_EXT { get; set; }
        public Nullable<int> CD_EXT { get; set; }
        public Nullable<int> CD_LANCAMENTO { get; set; }
        public int TP_LANCAMENTO { get; set; }
        public Nullable<decimal> VL_COMISSAO { get; set; }
        public Nullable<decimal> VL_JRO_CMS { get; set; }
        public Nullable<decimal> VL_COMISSAO_ASS { get; set; }
        public Nullable<decimal> VAL_JRO_CMS_ASS { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_PAGAMENTO { get; set; }
        public string ST_LANCAMENTO { get; set; }
        public Nullable<int> CD_EVENTO { get; set; }
        public Nullable<System.DateTime> DT_EVO_DM { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public string CD_ORIGEM { get; set; }
        public Nullable<decimal> VL_CMS_CUSTO { get; set; }
        public string TP_ENDOSSO { get; set; }
        public string CD_SISTEMA { get; set; }
        public int TP_COMISSAO { get; set; }
        public Nullable<short> CD_PARCELA_BAIXADA { get; set; }
        public long NR_SEQUENCIA { get; set; }
        public string IN_LANCTO_MANUAL { get; set; }
        public Nullable<int> CD_EVENTO_PAGNET { get; set; }
    }
}
