//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_RECEPCAO_AUXILIAR
    {
        public string CD_ORIGEM { get; set; }
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public string CD_ENDOSSO_CANCELAMENTO { get; set; }
        public short CD_PARCELA { get; set; }
        public string CD_RAMO { get; set; }
        public string CD_STM { get; set; }
        public System.DateTime DT_MOVIMENTO { get; set; }
        public string DT_BASE { get; set; }
        public int CD_SEG { get; set; }
        public int CD_EVT { get; set; }
        public System.DateTime DT_CARGA { get; set; }
        public string CD_ENDOSSO_EMISSAO { get; set; }
    }
}
