//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_NATUREZA
    {
        public string CD_NATUREZA { get; set; }
        public string DS_NATUREZA { get; set; }
        public string CD_NATUREZA_PISIS { get; set; }
        public string DS_NATUREZA_PISIS { get; set; }
        public string CD_NATUREZA_SYBASE { get; set; }
        public string DS_NATUREZA_SYBASE { get; set; }
    }
}
