//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_PARAMETRO_ARQUIVO
    {
        public int CD_EVENTO { get; set; }
        public string CD_SISTEMA { get; set; }
        public string DS_ARQUIVO { get; set; }
        public string CD_ORIGEM { get; set; }
        public Nullable<bool> TP_SINAL { get; set; }
        public Nullable<int> TP_MOVIMENTO { get; set; }
        public Nullable<int> TP_SINISTRO { get; set; }
        public Nullable<bool> IN_VALOR_TOTAL { get; set; }
        public Nullable<bool> IN_VALOR_CORRECAO_MONETARIA { get; set; }
        public Nullable<bool> IN_VALOR_JUROS { get; set; }
        public Nullable<bool> IN_VALOR_OSCILACAO_CAMBIAL { get; set; }
        public Nullable<bool> IN_CONTENCIOSO { get; set; }
    }
}
