//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_SUN_EVENTOS
    {
        public int ID_EVENTO_CONTABIL { get; set; }
        public int ID_LANCAMENTO { get; set; }
        public int ID_HISTORICO { get; set; }
        public string FLG_DSP { get; set; }
        public string FLG_RMO { get; set; }
        public string FLG_FIL { get; set; }
        public string FLG_CEC { get; set; }
        public string FLG_CTI { get; set; }
        public string FLG_DCM { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    
        public virtual TB_ODS_SUN_LANCAMENTOS TB_ODS_SUN_LANCAMENTOS { get; set; }
    }
}
