//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_HIERARQUIA
    {
        public string CD_CORR { get; set; }
        public string dcrCO { get; set; }
        public string codGC { get; set; }
        public string dcrGC { get; set; }
        public Nullable<short> cccGC { get; set; }
        public string codSU { get; set; }
        public string dcrSU { get; set; }
        public Nullable<short> cccSU { get; set; }
        public string tcdSU { get; set; }
        public string codPO { get; set; }
        public string dcrPO { get; set; }
        public Nullable<short> cccPO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    
        public virtual TB_ODS_CORRETOR TB_ODS_CORRETOR { get; set; }
    }
}
