//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_PERFIL_COTACAO
    {
        public string CD_COTACAO { get; set; }
        public System.DateTime DATA_COTACAO { get; set; }
        public int CD_ITEM { get; set; }
        public string CD_PERGUNTA { get; set; }
        public string DS_PERGUNTA { get; set; }
        public string DS_RESPOSTA { get; set; }
        public string TP_RESPOSTA { get; set; }
    }
}
