//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_SEGURADORA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ODS_SEGURADORA()
        {
            this.TB_ODS_EMISSAO = new HashSet<TB_ODS_EMISSAO>();
            this.TB_ODS_PARTCOSSEGURO = new HashSet<TB_ODS_PARTCOSSEGURO>();
        }
    
        public string CD_SEG { get; set; }
        public string NM_SEG { get; set; }
        public string CD_GRUPO { get; set; }
        public string NM_GRUPO { get; set; }
        public string DT_PERIODO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_EMISSAO> TB_ODS_EMISSAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_PARTCOSSEGURO> TB_ODS_PARTCOSSEGURO { get; set; }
    }
}
