//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_REGIAO_CEP_UF
    {
        public string CD_ESTADO { get; set; }
        public string CD_CEP_INICIO { get; set; }
        public string CD_CEP_FIM { get; set; }
    }
}
