//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_EXTRATO_COMISSAO
    {
        public int CD_EXTRATO { get; set; }
        public string CD_CORR { get; set; }
        public string ST_SITUACAO { get; set; }
        public string NR_MES_REF { get; set; }
        public Nullable<decimal> VL_CMS_BRT { get; set; }
        public Nullable<decimal> VL_RPE_CMS { get; set; }
        public Nullable<decimal> VL_IMT { get; set; }
        public Nullable<decimal> VL_CMS_LQD { get; set; }
        public Nullable<decimal> VL_CMS_TBT { get; set; }
        public Nullable<decimal> VL_CMS_NAO_TBT { get; set; }
        public Nullable<decimal> VL_CMS_ASS { get; set; }
        public Nullable<System.DateTime> DT_FECHAMENTO { get; set; }
        public Nullable<System.DateTime> DT_PAGAMENTO { get; set; }
        public Nullable<int> QT_LANCAMENTO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public Nullable<decimal> VL_CMS_CUSTO { get; set; }
        public int CD_EVENTO { get; set; }
        public Nullable<System.DateTime> DT_EVO_DM { get; set; }
        public int TP_COMISSAO { get; set; }
    }
}
