//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_PRODUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ODS_PRODUTO()
        {
            this.TB_ODS_EMISSAO = new HashSet<TB_ODS_EMISSAO>();
        }
    
        public string CD_PROD { get; set; }
        public string DS_PROD { get; set; }
        public string CD_RAMO { get; set; }
        public string NM_GRUPO { get; set; }
        public string NM_SUB_GRUPO { get; set; }
        public string NR_PROC_SUSEP { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public string CD_CLASSIFICACAO { get; set; }
        public string TP_PRODUTO { get; set; }
        public string TP_ITEM { get; set; }
        public Nullable<bool> IN_ACEITA_APOLICE_ABERTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_EMISSAO> TB_ODS_EMISSAO { get; set; }
        public virtual TB_ODS_RAMO TB_ODS_RAMO { get; set; }
    }
}
