//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_PLANO_CONTAS
    {
        public string CD_SISTEMA { get; set; }
        public int CD_EVENTO { get; set; }
        public string DS_EVENTO { get; set; }
        public string CD_OBJETO { get; set; }
        public string DS_OBJETO { get; set; }
        public string NR_CONTA { get; set; }
        public string TP_DEB_CRED { get; set; }
        public System.DateTime DT_INIVIG { get; set; }
        public System.DateTime DT_FIMVIG { get; set; }
        public string CD_HISTORICO { get; set; }
        public string CD_TIPO_RESSEGURO { get; set; }
        public string CD_LANCAMENTO { get; set; }
        public string DS_LANCAMENTO { get; set; }
        public string CD_TIPO_CONTA { get; set; }
        public string CD_TIPO_MOEDA { get; set; }
    }
}
