//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_ENQUADRAMENTO
    {
        public string CD_PROD { get; set; }
        public System.DateTime DT_INI_VIG { get; set; }
        public string CD_ENQDR { get; set; }
        public string DCR_ENQDR { get; set; }
        public Nullable<System.DateTime> DT_FIM_VIG { get; set; }
        public string CD_ENQDR_GRUPO { get; set; }
        public string CD_CLAUS { get; set; }
        public string CD_OCUP { get; set; }
        public Nullable<System.DateTime> DT_INCL { get; set; }
        public Nullable<System.DateTime> DT_ALT { get; set; }
        public string NOM_USR_INCL { get; set; }
        public string NOM_USR_ALT { get; set; }
        public string CD_ENQDR_EXT { get; set; }
        public string IND_QUEST { get; set; }
        public string CD_ENQDR_ROUBO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    }
}
