//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_CREDITOS_ANTECIPADOS
    {
        public long ID_FOLLOWUP { get; set; }
        public int CD_EVENTO { get; set; }
        public string CD_RAMO { get; set; }
        public string CD_CIA { get; set; }
        public string CD_CONTRATO { get; set; }
        public int CD_EMISSAO { get; set; }
        public int CD_PARCELA { get; set; }
        public string CD_NOSSO_NUMERO { get; set; }
        public string CD_PROPOSTA { get; set; }
        public System.DateTime DT_PROPOSTA { get; set; }
        public string CD_PRODUTO { get; set; }
        public Nullable<System.DateTime> DT_PAGAMENTO { get; set; }
        public System.DateTime DT_MOVIMENTO { get; set; }
        public string CD_BANCO { get; set; }
        public string CD_AGENCIA { get; set; }
        public string NR_CONTACORRENTE { get; set; }
        public string CD_MOEDA { get; set; }
        public string CD_BOLETO { get; set; }
        public Nullable<decimal> VL_PREMIO_LIQ { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public Nullable<System.DateTime> DT_EVO_DM { get; set; }
        public Nullable<long> ID_AVISO_CREDITO { get; set; }
    }
}
