//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_F_ITEM_QUESTIONARIO
    {
        public string NR_APOLICE { get; set; }
        public string NR_ENDOSSO { get; set; }
        public int CD_ITEM { get; set; }
        public string TP_ENDOSSO { get; set; }
        public string CD_ORIGEM { get; set; }
        public int CD_PERGUNTA { get; set; }
        public string DS_PERGUNTA { get; set; }
        public int CD_RESPOSTA { get; set; }
        public string DS_RESPOSTA { get; set; }
        public string DS_RESPOSTA_ITEM { get; set; }
        public int TP_RESPOSTA { get; set; }
        public System.DateTime DT_CARGA { get; set; }
        public long ID_SEQUENCIA { get; set; }
        public Nullable<System.DateTime> DT_PROCESSAMENTO { get; set; }
        public string NM_ARQUIVO { get; set; }
        public string DS_OBSERVACAO { get; set; }
    }
}
