//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_CONTROLE_DATA_ETL
    {
        public Nullable<System.DateTime> DTINIVIG { get; set; }
        public Nullable<System.DateTime> DTFIMVIG { get; set; }
        public Nullable<System.DateTime> DTPRIMMES { get; set; }
        public Nullable<System.DateTime> DTULTMES { get; set; }
        public Nullable<System.DateTime> DT_PROCESSAMENTO { get; set; }
        public string IN_CARGA_NORMAL { get; set; }
    }
}
