//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_AVISO_CREDITO_FOLLOWUP
    {
        public long ID_FOLLOWUP { get; set; }
        public int CD_TIPO_OCORRENCIA_FOLLOWUP { get; set; }
        public long ID_AVISO_DETALHE { get; set; }
        public long ID_AVISO_CREDITO { get; set; }
        public Nullable<decimal> VL_MOVIMENTO { get; set; }
        public Nullable<System.DateTime> DT_MOVIMENTO { get; set; }
        public Nullable<System.DateTime> DT_OCORRENCIA { get; set; }
        public Nullable<System.DateTime> DT_RECEBIMENTO_CREDITO { get; set; }
        public Nullable<decimal> VL_RECEBIDO_PAGAMENTO { get; set; }
        public Nullable<int> CD_SITUACAO_FOLLOWUP { get; set; }
        public Nullable<int> CD_TIPO_OCORRENCIA_PARCELA_TITULO { get; set; }
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public Nullable<short> CD_PARCELA { get; set; }
        public string CD_SEG { get; set; }
        public string CD_MOEDA { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public Nullable<System.DateTime> DT_EVO_DM { get; set; }
        public Nullable<int> NUM_SEQ { get; set; }
    }
}
