//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_AGENTECOBRADOR
    {
        public string CD_AGENTE { get; set; }
        public string TP_AGENTE { get; set; }
        public string CD_BANCO { get; set; }
        public string CD_AGENCIA { get; set; }
        public string CD_CONTA { get; set; }
        public string CD_CNPJ { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public Nullable<bool> IN_RETEM_IOF { get; set; }
        public string CD_CARTEIRA { get; set; }
    }
}
