//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_DETALHE_SINISTRO
    {
        public string CD_AVS_SGO { get; set; }
        public string NM_CIDADE { get; set; }
        public string NM_UF { get; set; }
        public string NM_CONDUTOR { get; set; }
        public string NM_SEXO { get; set; }
        public Nullable<int> NR_IDADE { get; set; }
        public string NM_ESTADO_CIVIL { get; set; }
        public Nullable<System.DateTime> DT_HABILITACAO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public string CD_STM { get; set; }
        public string ID_MOVTOPAGTOSINISTRO { get; set; }
        public string CD_CEP_OCORRENCIA { get; set; }
        public Nullable<decimal> NR_CPF { get; set; }
        public short CD_PARENT { get; set; }
        public Nullable<System.DateTime> DT_NASCIMENTO { get; set; }
        public string NM_OFICINA { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_VISTORIA { get; set; }
        public string TP_REPARO { get; set; }
        public string NM_RESPONSAVEL_LOCAL { get; set; }
        public string CD_CEP_OFICINA { get; set; }
        public string CD_UF_OFICINA { get; set; }
        public string NM_CIDADE_OFICINA { get; set; }
        public string CD_ENDOSSO { get; set; }
        public string CD_ORIGEM { get; set; }
        public string TP_ENDOSSO { get; set; }
        public int CD_ITEM { get; set; }
    
        public virtual TB_ODS_SINISTRO TB_ODS_SINISTRO { get; set; }
    }
}
