//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_ENTIDADE
    {
        public int CD_PESS { get; set; }
        public string CD_CPF_CNPJ { get; set; }
        public string CD_ENTIDADE { get; set; }
        public string DS_ENTIDADE { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    }
}
