//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_F_EMISSAO
    {
        public string CD_LIDER { get; set; }
        public string NR_APOLICE_DW { get; set; }
        public string TP_ENDOSSO { get; set; }
        public string NR_ENDOSSO_DW { get; set; }
        public int CD_PARCELA { get; set; }
        public string CD_RAMO_SUSEP { get; set; }
        public int CD_ITEM { get; set; }
        public string CD_COBERTURA { get; set; }
        public string CD_CORRETOR { get; set; }
        public string CD_ORIGEM { get; set; }
        public string CD_COSSEGURADOR { get; set; }
        public int TP_COBERTURA { get; set; }
        public string CD_SISTEMA { get; set; }
        public int CD_EVENTO { get; set; }
        public string CD_REVENDA { get; set; }
        public bool IN_CORRETOR_LIDER { get; set; }
        public System.DateTime DT_OPERACAO { get; set; }
        public int TP_COMISSAO { get; set; }
        public string CD_MOEDA { get; set; }
        public System.DateTime DT_EMISSAO { get; set; }
        public System.DateTime DT_INICIO_VIGENCIA { get; set; }
        public System.DateTime DT_FINAL_VIGENCIA { get; set; }
        public string CD_PROPOSTA { get; set; }
        public System.DateTime DT_PROPOSTA { get; set; }
        public System.DateTime DT_VENCIMENTO_PARCELA { get; set; }
        public string NM_SEGURADO { get; set; }
        public string CD_CPF_CNPJ_SEGURADO { get; set; }
        public string CD_PRODUTO { get; set; }
        public decimal PC_COSSEGURO { get; set; }
        public decimal PC_COMISSAO_COSSEGURO { get; set; }
        public int QT_ITENS { get; set; }
        public decimal VL_IMPORTANCIA_SEGURADA { get; set; }
        public decimal VL_PREMIO_LIQUIDO { get; set; }
        public decimal VL_ADICIONAL_FRAC { get; set; }
        public decimal VL_CUSTO_APOLIC { get; set; }
        public decimal VL_IOF { get; set; }
        public decimal VL_COMISSAO { get; set; }
        public decimal VL_CUSTO_COMISSAO { get; set; }
        public decimal PC_COMISSAO { get; set; }
        public decimal PC_PARTICIPACAO_CORRETOR { get; set; }
        public string CD_AGENTE_COBRADOR { get; set; }
        public string CD_BOLETO { get; set; }
        public string CD_NOSSO_NUMERO { get; set; }
        public string CD_APOLICE_ORIGINAL { get; set; }
        public string CD_ENDOSSO_ORIGINAL { get; set; }
        public int TP_EMISSAO { get; set; }
        public System.DateTime DT_CALCULO { get; set; }
        public System.DateTime DT_REFERENCIA { get; set; }
        public int TP_RENOVACAO { get; set; }
        public string CD_CIA_RENOVACAO { get; set; }
        public string CD_CEP_ITEM { get; set; }
        public string CD_UF_RISCO { get; set; }
        public string CD_CEP_SEGURADO { get; set; }
        public string CD_UF_SEGURADO { get; set; }
        public decimal VL_FRANQUIA { get; set; }
        public string IN_STATUS_COBERTURA { get; set; }
        public Nullable<System.DateTime> DT_NASCIMENTO { get; set; }
        public System.DateTime DT_PROTOCOLO { get; set; }
        public Nullable<int> CD_GRUPO_FINANCEIRO { get; set; }
        public string UF_ORGAO_EMISSOR { get; set; }
        public string CD_CPF_VENDEDOR { get; set; }
        public string CD_CONTRATO { get; set; }
        public Nullable<int> CD_BONUS { get; set; }
        public decimal TX_PERCENTUAL_BONUS { get; set; }
        public string CD_FORMA_PAGAMENTO { get; set; }
        public short NR_PARCELAS { get; set; }
        public string DS_INFO0 { get; set; }
        public string DS_INFO1 { get; set; }
        public string DS_INFO2 { get; set; }
        public string DS_INFO3 { get; set; }
        public string DS_VERSAO_CALCULO { get; set; }
        public Nullable<int> QT_VEICULOS { get; set; }
        public decimal TX_DESCONTO_COMERCIAL { get; set; }
        public decimal VL_DESCONTO_FROTA { get; set; }
        public decimal VL_DESCONTO_FIDELIDADE { get; set; }
        public decimal TX_COEFICIENTE_COMISSAO { get; set; }
        public decimal TX_COMISSAO_BASE { get; set; }
        public decimal TX_COMISSAO_APLICADA { get; set; }
        public Nullable<int> CD_ACESSORIO { get; set; }
        public decimal VL_PREMIO_ITEM { get; set; }
        public decimal TX_PREMIO_TOTAL { get; set; }
        public string DS_FRANQUIA { get; set; }
        public string CD_CI_ANTERIOR { get; set; }
        public string CD_SUCURSAL_ANTERIOR { get; set; }
        public Nullable<int> CD_ITEM_ANTERIOR { get; set; }
        public string CD_TIPO_MODALIDADE { get; set; }
        public string CD_VEICULO { get; set; }
        public string CD_FIPE_VEICULO { get; set; }
        public Nullable<int> CD_CATEGORIA_TARIFARIA { get; set; }
        public string CD_GRUPO_TARIFARIO { get; set; }
        public decimal TX_FATOR_AJUSTE { get; set; }
        public Nullable<short> TP_UTILIDADE_VEICULO { get; set; }
        public string DS_NEGOCIO_VEICULO { get; set; }
        public Nullable<bool> IN_VEICULO_ZERO { get; set; }
        public string TP_COMBUSTIVEL { get; set; }
        public Nullable<int> NR_PASSAGEIROS { get; set; }
        public Nullable<int> NR_ANO_FABRICACAO { get; set; }
        public Nullable<int> NR_ANO_MODELO { get; set; }
        public string DS_PLACA_VEICULO { get; set; }
        public string DS_CHASSI_VEICULO { get; set; }
        public string CD_VISTORIA { get; set; }
        public Nullable<System.DateTime> DT_VISTORIA { get; set; }
        public string CD_ENDOSSADO { get; set; }
        public short TP_MOVIMENTO_COBRANCA { get; set; }
        public System.DateTime DT_CARGA { get; set; }
        public long ID_SEQUENCIA { get; set; }
        public Nullable<System.DateTime> DT_PROCESSAMENTO { get; set; }
        public string NM_ARQUIVO { get; set; }
        public string DS_OBSERVACAO { get; set; }
        public string CD_APOLICE_ANTERIOR { get; set; }
        public string CD_ENDOSSO_ANTERIOR { get; set; }
        public Nullable<bool> IN_SEGURADORA_LIDER { get; set; }
        public Nullable<decimal> PC_PARTICIPACAO_SEGURADORA { get; set; }
        public Nullable<System.DateTime> DT_EMISSAO_ORIGINAL { get; set; }
    }
}
