//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_PARAMETRO
    {
        public string CD_PARAMETRO { get; set; }
        public string DS_PARAMETRO { get; set; }
        public string CD_SUB_PARAMETRO { get; set; }
        public string DS_SUB_PARAMETRO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
    }
}
