//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_SUB_REGIONAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ODS_SUB_REGIONAL()
        {
            this.TB_ODS_SUCURSAL = new HashSet<TB_ODS_SUCURSAL>();
        }
    
        public string CD_SUB_REGIONAL { get; set; }
        public string CD_REGIONAL { get; set; }
        public string NM_SUB_REGIONAL { get; set; }
        public Nullable<System.DateTime> DAT_CARGA { get; set; }
    
        public virtual TB_ODS_REGIONAL TB_ODS_REGIONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_SUCURSAL> TB_ODS_SUCURSAL { get; set; }
    }
}
