//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_DAC_PARAMETRO
    {
        public string NR_CONTA { get; set; }
        public System.DateTime DT_INICIAL { get; set; }
        public Nullable<System.DateTime> DT_FINAL { get; set; }
        public string CD_SISTEMA { get; set; }
        public string DS_CONTA { get; set; }
    }
}
