//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_DETALHE_CLOSING_RATIO
    {
        public string CD_CONTRATO { get; set; }
        public int CD_ITEM { get; set; }
        public Nullable<System.DateTime> DATA_CONTRATO { get; set; }
        public string DS_DETALHE { get; set; }
        public string DS_NIVEL0 { get; set; }
        public string DS_NIVEL1 { get; set; }
        public string DS_NIVEL2 { get; set; }
        public string DS_NIVEL3 { get; set; }
        public string DS_NIVEL4 { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    }
}
