//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_DAC_CONTA_RATEIO
    {
        public string DT_BASE { get; set; }
        public int NR_CARGA { get; set; }
        public int NR_LINHA { get; set; }
        public string NR_CONTA { get; set; }
        public System.DateTime DT_LANCAMENTO { get; set; }
        public string TP_DEBITO_CREDITO { get; set; }
        public Nullable<decimal> VL_LANCAMENTO { get; set; }
        public string CD_RAMO { get; set; }
        public string CD_PRODUTO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public Nullable<System.DateTime> DT_EVO_DM { get; set; }
    }
}
