//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_PROPOSTA
    {
        public string CD_CONTRATO { get; set; }
        public System.DateTime DATA_PROPOSTA { get; set; }
        public int CD_ITEM { get; set; }
        public string TP_REGISTRO { get; set; }
        public string CD_PRODUTO { get; set; }
        public string CD_CORRETOR { get; set; }
        public string NM_SEGURADO { get; set; }
        public string NR_CPF_CNPJ { get; set; }
        public string CD_ORIGEM { get; set; }
        public string DS_ORIGEM { get; set; }
        public string CD_CEP { get; set; }
        public Nullable<double> CD_CATEG_BONUS { get; set; }
        public string CD_REGIAO_TARIFARIA { get; set; }
        public string TP_RENOVACAO { get; set; }
        public string DS_RENOVACAO { get; set; }
        public Nullable<decimal> VL_PREMIO_TOTAL { get; set; }
        public Nullable<System.DateTime> DT_EVO_DM { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    }
}
