//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_DETALHE_PARCELA
    {
        public string CD_AGENTE { get; set; }
        public Nullable<System.DateTime> DT_VENCIMENTO { get; set; }
        public Nullable<System.DateTime> DT_PAGAMENTO { get; set; }
        public string CD_BOLETO { get; set; }
        public string CD_LINHA { get; set; }
        public string CD_DOCUMENTO { get; set; }
        public string CD_AGENCIA { get; set; }
        public string CD_CONTA { get; set; }
        public string CD_NOSSO_NUM { get; set; }
        public string TP_ENDOSSO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public string CD_ORIGEM { get; set; }
        public string CD_ENDOSSO { get; set; }
        public string CD_PARCELA { get; set; }
        public string CD_SEG { get; set; }
        public string CD_STM { get; set; }
        public string CD_APOLICE { get; set; }
    
        public virtual TB_ODS_TITULOS TB_ODS_TITULOS { get; set; }
    }
}
