//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_EVENTOS_CONTABEIS
    {
        public int ID_EVENTO_CONTABIL { get; set; }
        public int ID_EVENTO { get; set; }
        public int ID_OBJETO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    }
}
