//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_CADASTRO_ERROS
    {
        public string NM_PROCEDURE { get; set; }
        public int CD_ERRO { get; set; }
        public string DS_ERRO { get; set; }
    }
}
