//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_REGIAO_PROPOSTA
    {
        public string CD_CONTRATO { get; set; }
        public System.DateTime DT_PROPOSTA { get; set; }
        public int CD_ITEM { get; set; }
        public string CD_UF { get; set; }
        public string DS_REGIAO { get; set; }
        public string DS_CIDADE { get; set; }
        public string CD_CEP { get; set; }
    }
}
