//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_RESSEGURO_GERAL
    {
        public int ID_RESSEGURO { get; set; }
        public string CD_PRODUTO { get; set; }
        public string CD_PRODUTO_VERSAO { get; set; }
        public System.DateTime DT_INICIO_VIGENCIA { get; set; }
        public System.DateTime DT_FINAL_VIGENCIA { get; set; }
        public Nullable<decimal> VL_MINIMO_ED { get; set; }
        public Nullable<decimal> VL_MAXIMO_ED { get; set; }
        public Nullable<decimal> VL_MINIMO_ER { get; set; }
        public Nullable<decimal> VL_MAXIMO_ER { get; set; }
        public string TP_PREMIO { get; set; }
        public string TP_GRUPO { get; set; }
        public string TP_SUBPRODUTO { get; set; }
        public Nullable<decimal> VL_MINIMO_ED_RESTRICAO { get; set; }
        public System.DateTime DT_INICIO_VIGENCIA_VERSAO { get; set; }
        public string NM_CONTRATO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    }
}
