//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_F_SINISTRO
    {
        public string ID_MOVTOPAGTOSINISTRO { get; set; }
        public string NR_SINISTRO { get; set; }
        public string CD_ORIGEM { get; set; }
        public string CD_LIDER { get; set; }
        public string CD_SISTEMA { get; set; }
        public int CD_EVENTO { get; set; }
        public string NR_APOLICE_DW { get; set; }
        public string TP_ENDOSSO { get; set; }
        public string NR_ENDOSSO_DW { get; set; }
        public int CD_ITEM { get; set; }
        public string CD_COBERTURA { get; set; }
        public System.DateTime DT_AVISO { get; set; }
        public System.DateTime DT_COMUNICACAO { get; set; }
        public System.DateTime DT_OCORRENCIA { get; set; }
        public string CD_UF_OCORRENCIA { get; set; }
        public string CD_CEP_OCORRENCIA { get; set; }
        public string CD_CAUSA { get; set; }
        public string DS_CAUSA_SINISTRO { get; set; }
        public string DS_INFO0 { get; set; }
        public string DS_INFO1 { get; set; }
        public string DS_INFO2 { get; set; }
        public string DS_INFO3 { get; set; }
        public short TP_PERDA { get; set; }
        public string CD_COSSEGURADOR { get; set; }
        public System.DateTime DT_MOVIMENTO { get; set; }
        public decimal VL_MOVIMENTO { get; set; }
        public decimal VL_FRANQUIA { get; set; }
        public string CD_MOEDA { get; set; }
        public string NR_CPF_CONDUTOR { get; set; }
        public string NM_CONDUTOR { get; set; }
        public string TP_SEXO { get; set; }
        public Nullable<System.DateTime> DT_NASCIMENTO { get; set; }
        public string CD_ESTADO_CIVIL { get; set; }
        public Nullable<System.DateTime> DT_HABILITACAO { get; set; }
        public string NM_CIDADE { get; set; }
        public string CD_VEICULO { get; set; }
        public string TP_ANALISEVISTORIA { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_VISTORIA { get; set; }
        public Nullable<bool> IN_SINDICANCIA { get; set; }
        public string CD_CPF_CNPJ_SEGURADO { get; set; }
        public string NM_SEGURADO { get; set; }
        public string NM_ANALISTA { get; set; }
        public string NM_CIDADE_OFICINA { get; set; }
        public string NM_OFICINA { get; set; }
        public string CD_CEP_OFICINA { get; set; }
        public string CD_UF_OFICINA { get; set; }
        public string NM_RESPONSAVEL_LOCAL { get; set; }
        public string NR_CPF_BENEFICIARIO { get; set; }
        public string NM_BENEFICIARIO { get; set; }
        public int QT_BENEFICIARIOS { get; set; }
        public string CD_AGENCIA { get; set; }
        public string CD_AGENCIA_SEGURADORA { get; set; }
        public string CD_BANCO { get; set; }
        public string CD_BANCO_SEGURADORA { get; set; }
        public string NR_CONTA_CORRENTE { get; set; }
        public string NR_CONTA_CORRENTE_SEGURADORA { get; set; }
        public string NR_TRANSACAO { get; set; }
        public Nullable<short> TP_PAGAMENTO { get; set; }
        public string TP_VINCULO_CONDUTOR_SEGURADO { get; set; }
        public long ID_SEQUENCIA { get; set; }
        public System.DateTime DT_CARGA { get; set; }
        public Nullable<System.DateTime> DT_PROCESSAMENTO { get; set; }
        public string NM_ARQUIVO { get; set; }
        public string DS_OBSERVACAO { get; set; }
    }
}
