//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_ITEM_PPNG
    {
        public string NUM_APOLICE { get; set; }
        public string NUM_ENDOSSO { get; set; }
        public int COD_ITEM { get; set; }
        public string ORIGEM_DOCTO { get; set; }
        public string TIP_EMIS { get; set; }
        public Nullable<System.DateTime> DAT_INI_VIGENCIA { get; set; }
        public Nullable<System.DateTime> DAT_FIM_VIGENCIA { get; set; }
        public System.DateTime DT_STG_CARGA { get; set; }
    }
}
