//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_CONTROLE_EMISSAO_ANTECIPADA
    {
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public string CD_PROPOSTA { get; set; }
        public string CD_APOLICE_ORIGINAL { get; set; }
        public string CD_ENDOSSO_ORIGINAL { get; set; }
        public Nullable<System.DateTime> DT_EMISSAO { get; set; }
        public Nullable<System.DateTime> DT_INI_VIG { get; set; }
        public Nullable<System.DateTime> DT_FIM_VIG { get; set; }
        public Nullable<System.DateTime> DT_REFERENCIA { get; set; }
        public Nullable<int> CD_MOEDA { get; set; }
        public string CD_SISTEMA { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public Nullable<System.DateTime> DT_EMISSAO_ORI { get; set; }
        public Nullable<int> IN_EMITIDO { get; set; }
        public string CD_ORIGEM { get; set; }
        public string TP_ENDOSSO { get; set; }
    
        public virtual TB_ODS_EMISSAO TB_ODS_EMISSAO { get; set; }
    }
}
