//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_OCORRENCIAS_OSCILACAO_CAMBIAL
    {
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public string TP_ENDOSSO { get; set; }
        public short CD_PARCELA { get; set; }
        public string CD_RAMO { get; set; }
        public string CD_SEG { get; set; }
        public string CD_STM { get; set; }
        public long ID_PARCELA { get; set; }
        public long ID_PARCELA_OCORRENCIA { get; set; }
        public Nullable<System.DateTime> DT_OCORRENCIA { get; set; }
        public Nullable<decimal> VL_CUSTO { get; set; }
        public Nullable<decimal> VL_ADICIONAL_FRACIONADO { get; set; }
        public Nullable<decimal> VL_PREMIO_LIQUIDO { get; set; }
        public Nullable<decimal> VL_ASSISTENCIA { get; set; }
        public Nullable<decimal> VL_DIFERENCA { get; set; }
        public Nullable<decimal> VL_IOF { get; set; }
        public Nullable<decimal> VL_JUROS { get; set; }
        public Nullable<decimal> VL_MULTA { get; set; }
        public Nullable<decimal> VL_PREMIO_PAGO { get; set; }
        public Nullable<decimal> VL_PREMIO_TOTAL { get; set; }
        public Nullable<decimal> VL_VISTORIA { get; set; }
        public Nullable<decimal> VL_CAMBIO { get; set; }
        public Nullable<decimal> VL_DIFERENCA_PREMIO { get; set; }
        public Nullable<decimal> VL_COBRANCA_VISTORIA { get; set; }
        public string CD_MOEDA { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public Nullable<System.DateTime> DT_EVO_DM { get; set; }
        public Nullable<long> NUM_SEQ { get; set; }
    }
}
