//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_FIPECAFI_SINISTRO
    {
        public int CD_MOV { get; set; }
        public string CD_CIA { get; set; }
        public string DT_BASE { get; set; }
        public Nullable<double> TP_MOV { get; set; }
        public string CD_RAMO { get; set; }
        public string NR_SINISTRO { get; set; }
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public Nullable<int> CD_ITEM { get; set; }
        public string CD_COBERTURA { get; set; }
        public string DT_INI_VIG { get; set; }
        public string DT_FIM_VIG { get; set; }
        public string DT_REGISTRO { get; set; }
        public string DT_AVISO { get; set; }
        public string DT_OCOR { get; set; }
        public string DT_PAGAMENTO { get; set; }
        public decimal VL_COSS_CED { get; set; }
        public decimal VL_COSS_AC { get; set; }
        public decimal VL_PENDENTE { get; set; }
        public decimal VL_TOTAL { get; set; }
        public decimal VL_PAGO { get; set; }
        public decimal VL_DESP_SIN { get; set; }
        public decimal VL_SALV_PAGO { get; set; }
        public decimal VL_SALV_PENDENTE { get; set; }
        public decimal VL_RESSARCIMENTO { get; set; }
        public Nullable<double> TP_SINISTRO { get; set; }
        public decimal VL_RESS_CED { get; set; }
        public decimal VL_FRANQUIA { get; set; }
        public string CD_COSS { get; set; }
        public string DS_CAUSA { get; set; }
        public string DT_MOV { get; set; }
        public decimal VL_MOV { get; set; }
        public int NR_SEQ { get; set; }
        public Nullable<int> CD_MOEDA { get; set; }
        public string CD_ORIGEM { get; set; }
        public string CD_STM { get; set; }
        public int CD_EVT { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    }
}
