//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_OPERACIONAL
    {
        public int ID_OPERACIONAL { get; set; }
        public string CD_PROPOSTA { get; set; }
        public Nullable<System.DateTime> DT_VENCIMENTO { get; set; }
        public string CD_CORRETOR { get; set; }
        public string CD_CEP { get; set; }
        public string CD_PRODUTO { get; set; }
        public string CD_ROTINA { get; set; }
        public string DS_ROTINA { get; set; }
        public Nullable<int> QT_PARCELA { get; set; }
        public Nullable<int> CD_BONUS { get; set; }
        public string TP_RENOVA { get; set; }
        public string TP_PAGAMENTO { get; set; }
        public string TP_RECUSA { get; set; }
        public string TP_FONTE { get; set; }
        public string CD_LIDERANCA { get; set; }
        public string TP_DOCUMENTO { get; set; }
        public string TP_PREMIO_MINIMO { get; set; }
        public string CD_DETALHE { get; set; }
        public string TP_ENDOSSO { get; set; }
        public string TP_PROPOSTA { get; set; }
        public Nullable<int> QT_PROPOSTAS { get; set; }
        public string CD_GRUPO_FINANCEIRO { get; set; }
        public string NR_CPF_CNPJ { get; set; }
        public Nullable<int> QT_CALCULOS { get; set; }
        public string CD_CALCULO { get; set; }
        public Nullable<int> QT_ITENS { get; set; }
        public Nullable<System.DateTime> DT_EFETIVA { get; set; }
        public Nullable<int> QT_EMISSAO { get; set; }
        public string CD_ENTIDADE_ANTERIOR { get; set; }
        public Nullable<int> ID_PROCESSO { get; set; }
        public string TP_SITUACAO_EMIS { get; set; }
        public Nullable<System.DateTime> DT_PROCESSO { get; set; }
        public string CD_AGRUPAMENTO { get; set; }
        public Nullable<int> QT_TEMPO { get; set; }
        public Nullable<int> QT_OPERACAO { get; set; }
        public string TP_OPERACAO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    }
}
