//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_EMISSAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ODS_EMISSAO()
        {
            this.TB_ODS_COMISSAO_ANTECIPADA_DETALHES = new HashSet<TB_ODS_COMISSAO_ANTECIPADA_DETALHES>();
            this.TB_ODS_REVENDA = new HashSet<TB_ODS_REVENDA>();
            this.TB_ODS_ITEM = new HashSet<TB_ODS_ITEM>();
            this.TB_ODS_PARCELA_COMISSAO_ITEM_COBERTURA = new HashSet<TB_ODS_PARCELA_COMISSAO_ITEM_COBERTURA>();
            this.TB_ODS_PARTCORRETOR = new HashSet<TB_ODS_PARTCORRETOR>();
            this.TB_ODS_PARTCOSSEGURO = new HashSet<TB_ODS_PARTCOSSEGURO>();
            this.TB_ODS_PARTRESSEGURO = new HashSet<TB_ODS_PARTRESSEGURO>();
            this.TB_ODS_TITULOS = new HashSet<TB_ODS_TITULOS>();
        }
    
        public string CD_ORIGEM { get; set; }
        public string CD_APOLICE { get; set; }
        public string TP_ENDOSSO { get; set; }
        public string CD_ENDOSSO { get; set; }
        public string CD_PROPOSTA { get; set; }
        public string CD_APOLICE_ORIGINAL { get; set; }
        public string CD_ENDOSSO_ORIGINAL { get; set; }
        public string TP_COBR { get; set; }
        public string CD_AGRUPAMENTO { get; set; }
        public string CD_CORR { get; set; }
        public string TP_EMIS { get; set; }
        public string TP_MOVTO { get; set; }
        public string CD_PROD { get; set; }
        public string CD_CPF_CNPJ_SEG { get; set; }
        public string NM_SEGURADO { get; set; }
        public Nullable<System.DateTime> DT_EMISSAO_ORI { get; set; }
        public Nullable<System.DateTime> DT_EMISSAO { get; set; }
        public Nullable<System.DateTime> DT_INI_VIG { get; set; }
        public Nullable<System.DateTime> DT_FIM_VIG { get; set; }
        public Nullable<System.DateTime> DT_PROTOCOLO { get; set; }
        public Nullable<System.DateTime> DT_PROPOSTA { get; set; }
        public Nullable<System.DateTime> DT_CALCULO { get; set; }
        public Nullable<System.DateTime> DT_REFERENCIA { get; set; }
        public Nullable<int> CD_MOEDA { get; set; }
        public string QTD_PARCELA { get; set; }
        public Nullable<decimal> VL_PREM_LIQ { get; set; }
        public Nullable<decimal> VL_JUROS { get; set; }
        public Nullable<decimal> VL_DESCONTO { get; set; }
        public Nullable<decimal> VL_ASSIST { get; set; }
        public Nullable<decimal> VL_IOF { get; set; }
        public Nullable<decimal> VL_CUSTO_APOL { get; set; }
        public Nullable<decimal> VR_PREM_TOTL { get; set; }
        public Nullable<decimal> VR_PREM_RESS { get; set; }
        public Nullable<decimal> VR_PREM_COSS { get; set; }
        public Nullable<decimal> VL_COMISSAO { get; set; }
        public Nullable<decimal> VL_COMISSAO_ASS { get; set; }
        public Nullable<double> PC_ASSIST { get; set; }
        public string CD_SEG { get; set; }
        public string TP_RENOVA { get; set; }
        public string CD_CIA_RENOVA { get; set; }
        public string VS_CALCULO { get; set; }
        public Nullable<System.DateTime> DT_NASC { get; set; }
        public string CD_ORIGEM_DOCTO { get; set; }
        public Nullable<int> NR_ITENS { get; set; }
        public string CD_SUSEP { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public Nullable<System.DateTime> DT_EVO_DM { get; set; }
        public string CD_CPF_VENDEDOR { get; set; }
        public string CD_RAMO { get; set; }
        public Nullable<double> VL_MOEDA { get; set; }
        public Nullable<double> VL_PREMIO_NET { get; set; }
        public string TP_CALCULO_PREMIO { get; set; }
        public Nullable<double> VL_RISCO { get; set; }
        public Nullable<bool> IN_ESPECIFICACAO_COMPLETA { get; set; }
        public Nullable<decimal> VL_LMG { get; set; }
        public Nullable<double> VL_RISCOLUCROCESSANTE { get; set; }
        public string CD_ENDOSSO_MS10 { get; set; }
        public string IND_CONTRATO_FACULTATIVO { get; set; }
        public string IND_CONTRATO_DIFERENCIADO { get; set; }
        public string UF_SEG { get; set; }
        public string IN_UTILIZACAO_DAF { get; set; }
    
        public virtual TB_ODS_AGRUPAMENTO TB_ODS_AGRUPAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_COMISSAO_ANTECIPADA_DETALHES> TB_ODS_COMISSAO_ANTECIPADA_DETALHES { get; set; }
        public virtual TB_ODS_CONTROLE_EMISSAO_ANTECIPADA TB_ODS_CONTROLE_EMISSAO_ANTECIPADA { get; set; }
        public virtual TB_ODS_CORRETOR TB_ODS_CORRETOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_REVENDA> TB_ODS_REVENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_ITEM> TB_ODS_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_PARCELA_COMISSAO_ITEM_COBERTURA> TB_ODS_PARCELA_COMISSAO_ITEM_COBERTURA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_PARTCORRETOR> TB_ODS_PARTCORRETOR { get; set; }
        public virtual TB_ODS_TIPO_COBRANCA TB_ODS_TIPO_COBRANCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_PARTCOSSEGURO> TB_ODS_PARTCOSSEGURO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_PARTRESSEGURO> TB_ODS_PARTRESSEGURO { get; set; }
        public virtual TB_ODS_PRODUTO TB_ODS_PRODUTO { get; set; }
        public virtual TB_ODS_SEGURADORA TB_ODS_SEGURADORA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_TITULOS> TB_ODS_TITULOS { get; set; }
    }
}
