//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_ITEM_DETALHE
    {
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public int CD_ITEM { get; set; }
        public string CD_PLACA { get; set; }
        public string CD_CHASSI { get; set; }
        public Nullable<int> ANO_FAB { get; set; }
        public Nullable<int> ANO_MOD { get; set; }
        public Nullable<int> QTD_PORTAS { get; set; }
        public Nullable<int> QTD_PASS { get; set; }
        public string TP_COMBUSTIVEL { get; set; }
        public string GR_TARIFARIO { get; set; }
        public string CAT_TARIFARIA { get; set; }
        public string CD_FIPE { get; set; }
        public string IND_ZERO { get; set; }
        public string CD_CI { get; set; }
        public string CD_REG_RISCO { get; set; }
        public string TP_MODAL { get; set; }
        public string CD_FRQ { get; set; }
        public string CD_VEICULO { get; set; }
        public string DS_FRANQUIA { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public string CD_ORIGEM { get; set; }
        public string TP_ENDOSSO { get; set; }
        public string CD_USO_VEIC { get; set; }
        public Nullable<decimal> VL_FATOR_AJUSTE { get; set; }
        public string CD_VISTORIA { get; set; }
        public Nullable<System.DateTime> DT_VISTORIA { get; set; }
        public string TP_RENOVACAO { get; set; }
        public Nullable<double> PC_VARIACAO { get; set; }
        public string CD_TABELAIS { get; set; }
        public string Cd_Solicitacao_Inspecao { get; set; }
        public Nullable<System.DateTime> Dt_Agendamento { get; set; }
    
        public virtual TB_ODS_ITEM TB_ODS_ITEM { get; set; }
    }
}
