//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_ASSESSORIA
    {
        public string DT_BASE { get; set; }
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public string CD_ENDOSSO_ORIGINAL { get; set; }
        public int CD_PARCELA { get; set; }
        public string CD_RAMO { get; set; }
        public int CD_EVENTO { get; set; }
        public int NUM_SEQ { get; set; }
        public string TP_ENDOSSO { get; set; }
        public string CD_SISTEMA { get; set; }
        public string TP_EMISSAO { get; set; }
        public Nullable<System.DateTime> DT_EMISSAO { get; set; }
        public string CD_PRODUTO { get; set; }
        public Nullable<int> CD_MOEDA { get; set; }
        public string CD_CORRETOR { get; set; }
        public string CD_CORRETOR_AGR { get; set; }
        public Nullable<decimal> VL_PRE_LQD { get; set; }
        public Nullable<decimal> VL_PRE_COSS { get; set; }
        public string CD_FORMA_APURACAO { get; set; }
        public string CD_CLASSIFICACAO { get; set; }
        public System.DateTime DT_CARGA { get; set; }
        public string CD_ENDOSSO_CANCELADO { get; set; }
        public Nullable<System.DateTime> DT_APURACAO { get; set; }
        public Nullable<decimal> PC_APURACAO { get; set; }
        public Nullable<decimal> VL_ASSESSORIA { get; set; }
        public Nullable<System.DateTime> DT_EVO_DM { get; set; }
        public Nullable<System.DateTime> DT_EVO_MS10 { get; set; }
    }
}
