//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_TIPO_PAGAMENTO_SINISTRO
    {
        public int CD_TIPO_PAGAMENTO { get; set; }
        public string DS_TIPO_PAGAMENTO { get; set; }
        public Nullable<int> IN_PAGTO_INDENIZACAO { get; set; }
        public Nullable<int> IN_PAGTO_DESPESA { get; set; }
        public Nullable<int> IN_PAGTO_RESSARCIMENTO { get; set; }
        public Nullable<int> IN_PAGTO_SALVADO { get; set; }
        public Nullable<int> IN_AJUSTEPAGAMENTO { get; set; }
        public Nullable<int> IN_PAGAMENTOTOTAL { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    }
}
