//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_RESSEGURO_PARAMETRO
    {
        public string CD_CHAVE { get; set; }
        public string DS_VALOR { get; set; }
        public bool IN_ATIVO { get; set; }
        public string DS_DESCRICAO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    }
}
