//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_OCORRENCIAS
    {
        public int CD_SEQUENCIA { get; set; }
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public string CD_PARCELA { get; set; }
        public int CD_OCORRENCIA { get; set; }
        public System.DateTime DT_OCORRENCIA { get; set; }
        public int NR_LOTE { get; set; }
        public string TP_LOTE { get; set; }
        public Nullable<int> CD_MOEDA { get; set; }
        public Nullable<decimal> VL_PRE_PGO { get; set; }
        public Nullable<decimal> VL_MTA_ATS { get; set; }
        public Nullable<decimal> VL_IOF_RTD { get; set; }
        public Nullable<decimal> VL_DSO { get; set; }
        public Nullable<decimal> VL_ADC_FRC { get; set; }
        public Nullable<decimal> VL_ADC_FRC_DVI { get; set; }
        public string CD_BANCO_PAGTO { get; set; }
        public string TP_COBRANCA { get; set; }
        public Nullable<decimal> VL_MTA_DVI { get; set; }
        public Nullable<System.DateTime> DT_PGM { get; set; }
        public Nullable<decimal> VL_JRO_CBA { get; set; }
        public Nullable<decimal> VL_JRO_DVI { get; set; }
        public Nullable<decimal> VL_CAB { get; set; }
        public Nullable<decimal> VL_DFR_PRE { get; set; }
        public string TP_STU_OCR { get; set; }
        public Nullable<decimal> VL_DVL_COR { get; set; }
        public string FLG_BXA { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public Nullable<decimal> VL_PREM_CAMBIO { get; set; }
        public Nullable<decimal> VL_ADIC_CAMBIO { get; set; }
        public Nullable<decimal> VL_CUSTO_CAMBIO { get; set; }
        public Nullable<decimal> VL_ASSIST_CAMBIO { get; set; }
        public Nullable<System.DateTime> DT_EVO_DM { get; set; }
        public string CD_ORIGEM { get; set; }
        public string TP_ENDOSSO { get; set; }
        public string CD_STM { get; set; }
        public string CD_SEG { get; set; }
        public Nullable<decimal> VL_COB_VST { get; set; }
        public Nullable<int> ID_CONVENIO_CARTEIRA { get; set; }
        public Nullable<long> ID_AVISO_CREDITO { get; set; }
        public Nullable<short> FL_RETORNO_BANCARIO { get; set; }
        public string CD_BOLETO { get; set; }
        public string CD_LINHA { get; set; }
        public string CD_DOCUMENTO { get; set; }
        public string CD_NOSSO_NUMERO { get; set; }
        public Nullable<decimal> VL_TARIFA_BANCO { get; set; }
        public Nullable<decimal> VL_IOF_BANCO { get; set; }
    
        public virtual TB_ODS_TITULOS TB_ODS_TITULOS { get; set; }
    }
}
