//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ODS_ITEM()
        {
            this.TB_ODS_ITEM_COBERTURA = new HashSet<TB_ODS_ITEM_COBERTURA>();
            this.TB_ODS_ITEM_QUESTIONARIO = new HashSet<TB_ODS_ITEM_QUESTIONARIO>();
            this.TB_ODS_SINISTRO = new HashSet<TB_ODS_SINISTRO>();
        }
    
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public int CD_ITEM { get; set; }
        public string TP_ITEM { get; set; }
        public string INFO0 { get; set; }
        public string INFO1 { get; set; }
        public string INFO2 { get; set; }
        public string INFO3 { get; set; }
        public string INFO4 { get; set; }
        public string CD_CEP { get; set; }
        public string TP_PRODUTO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public string CD_CEP_INF { get; set; }
        public Nullable<decimal> VL_DESCONTO_FROTA { get; set; }
        public Nullable<decimal> VL_DESCONTO_COMERCIAL { get; set; }
        public Nullable<decimal> VL_DESCONTO_FIDELIDADE { get; set; }
        public string CD_LIDER_ANT { get; set; }
        public Nullable<decimal> PERC_COMISS { get; set; }
        public Nullable<decimal> PERC_COMISS_ORIG { get; set; }
        public string CD_ORIGEM { get; set; }
        public string TP_ENDOSSO { get; set; }
        public string COD_CONTRATO { get; set; }
        public string CD_VEICULO { get; set; }
        public string CD_PROD { get; set; }
        public string DS_ANO_FABRICACAO { get; set; }
        public Nullable<double> CD_BONUS { get; set; }
        public string CD_CAT_TARF { get; set; }
        public string CD_USO_VEICULO { get; set; }
        public string CD_REGIAO_SUSEP { get; set; }
        public Nullable<double> VL_RISCO { get; set; }
        public Nullable<double> VL_PREMIO_NET { get; set; }
        public string IN_COMPOE_LC { get; set; }
        public Nullable<double> VL_LMG { get; set; }
        public string END_GRUP { get; set; }
        public Nullable<double> END_VALORRISCO { get; set; }
        public string END_CLASSENQ { get; set; }
        public string CD_ENQDR { get; set; }
    
        public virtual TB_ODS_CEP TB_ODS_CEP { get; set; }
        public virtual TB_ODS_EMISSAO TB_ODS_EMISSAO { get; set; }
        public virtual TB_ODS_EMISSAO_ANTERIOR TB_ODS_EMISSAO_ANTERIOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_ITEM_COBERTURA> TB_ODS_ITEM_COBERTURA { get; set; }
        public virtual TB_ODS_ITEM_DETALHE TB_ODS_ITEM_DETALHE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_ITEM_QUESTIONARIO> TB_ODS_ITEM_QUESTIONARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_SINISTRO> TB_ODS_SINISTRO { get; set; }
    }
}
