//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_TIPO_COBRANCA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ODS_TIPO_COBRANCA()
        {
            this.TB_ODS_EMISSAO = new HashSet<TB_ODS_EMISSAO>();
        }
    
        public string TP_COBR { get; set; }
        public string DS_TIP_COBR { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_EMISSAO> TB_ODS_EMISSAO { get; set; }
    }
}
