//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_COTACAO_RE
    {
        public string CD_COTACAO { get; set; }
        public System.DateTime DATA_COTACAO { get; set; }
        public int CD_ITEM { get; set; }
        public string TP_REGISTRO { get; set; }
        public string CD_RAMO { get; set; }
        public string CD_PRODUTO { get; set; }
        public string CD_CORRETOR { get; set; }
        public string NM_SEGURADO { get; set; }
        public string NR_CPF_CNPJ { get; set; }
        public string NR_CPF_CNPJ_COTACAO { get; set; }
        public string CD_ORIGEM { get; set; }
        public string DS_ORIGEM { get; set; }
        public string TIPO_CLASSE { get; set; }
        public string OCUPACAO { get; set; }
        public string ENQUADRAMENTO { get; set; }
        public string CEP_RISCO { get; set; }
        public string TP_RENOVACAO { get; set; }
        public string DS_RENOVACAO { get; set; }
        public Nullable<decimal> IS_TOTAL { get; set; }
        public Nullable<decimal> VL_PREMIO_TOTAL { get; set; }
        public Nullable<int> QTDE_CALCULOS { get; set; }
        public Nullable<int> QTDE_EMISSOES { get; set; }
        public Nullable<System.DateTime> DT_EVO_DM { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public string ID_CHAVE_UNICIDADE { get; set; }
    }
}
