//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_SINISTRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ODS_SINISTRO()
        {
            this.TB_ODS_DETALHE_SINISTRO = new HashSet<TB_ODS_DETALHE_SINISTRO>();
        }
    
        public string CD_AVS_SGO { get; set; }
        public string CD_STM { get; set; }
        public string ID_MOVTOPAGTOSINISTRO { get; set; }
        public string CD_COB { get; set; }
        public Nullable<int> TP_MOV { get; set; }
        public Nullable<System.DateTime> DT_AVISO { get; set; }
        public Nullable<System.DateTime> DT_OCORR { get; set; }
        public Nullable<System.DateTime> DT_MOV { get; set; }
        public string TP_PERDA { get; set; }
        public string NM_SEGURADO { get; set; }
        public string CD_AGRUPAMENTO { get; set; }
        public string CD_EVT { get; set; }
        public string ST_STATUS { get; set; }
        public string INFO0 { get; set; }
        public string INFO1 { get; set; }
        public string INFO2 { get; set; }
        public string INFO3 { get; set; }
        public string TP_PRODUTO { get; set; }
        public Nullable<decimal> VL_IS { get; set; }
        public Nullable<decimal> VL_FRANQUIA { get; set; }
        public Nullable<decimal> VL_MOV { get; set; }
        public string CD_LIDER { get; set; }
        public string NM_ANALISTA { get; set; }
        public int CD_MOEDA { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public Nullable<System.DateTime> DT_EVO_DM { get; set; }
        public Nullable<int> CD_VARIACAO_MONETARIA { get; set; }
        public string CD_CAUSA { get; set; }
        public string CD_VEICULO { get; set; }
        public string DS_ANO_FABRICACAO { get; set; }
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public string CD_ORIGEM { get; set; }
        public string TP_ENDOSSO { get; set; }
        public int CD_ITEM { get; set; }
        public Nullable<bool> IN_SINDICANCIA { get; set; }
        public Nullable<int> ST_AVISOSINISTRO { get; set; }
        public Nullable<System.DateTime> DT_COMUNICACAO { get; set; }
        public string CD_CTR_RESSEGURO { get; set; }
        public string CD_AVS_SGO_MS10 { get; set; }
        public string UF_SEG { get; set; }
        public Nullable<long> ID_AVISO_CREDITO { get; set; }
        public string NM_STATUS { get; set; }
        public string CD_SINISTROLIDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_DETALHE_SINISTRO> TB_ODS_DETALHE_SINISTRO { get; set; }
        public virtual TB_ODS_ITEM TB_ODS_ITEM { get; set; }
    }
}
