//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_FIPECAFI_SERVICO
    {
        public string DT_BASE { get; set; }
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public Nullable<int> CD_ITEM { get; set; }
        public string CD_RAMO { get; set; }
        public int CD_PARCELA { get; set; }
        public string DT_EMISSAO { get; set; }
        public string DT_INI_VIG { get; set; }
        public string DT_FIM_VIG { get; set; }
        public string TP_SERVICO { get; set; }
        public decimal VL_PREMIO_EMITIDO { get; set; }
        public decimal VL_COMISSAO { get; set; }
        public string CD_CIA { get; set; }
        public int NR_SEQ { get; set; }
        public string CD_ORIGEM { get; set; }
        public Nullable<int> CD_MOEDA { get; set; }
        public string CD_STM { get; set; }
        public int CD_EVT { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    }
}
