//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_COTACAO_SSC
    {
        public decimal NR_COTACAO { get; set; }
        public int NR_SOLICITACAO { get; set; }
        public System.DateTime DT_ATUALIZACAO { get; set; }
        public Nullable<System.DateTime> DT_CRIACAO { get; set; }
        public string NR_CONTRATO { get; set; }
        public string NR_PROPOSTA { get; set; }
        public string DS_SUB_GRUPO_PRODUTO { get; set; }
        public string DS_PRODUTO { get; set; }
        public string CD_CORRETOR { get; set; }
        public string NM_SEGURADO { get; set; }
        public Nullable<decimal> NR_CPF_CNPJ_SEGURADO { get; set; }
        public string TP_SEGURO { get; set; }
        public Nullable<System.DateTime> DT_ULTIMA_ATUALIZACAO { get; set; }
        public string CD_SUBSCRITOR { get; set; }
        public string NM_FUNCIONARIO { get; set; }
        public Nullable<short> CD_STATUS { get; set; }
        public string DS_STATUS { get; set; }
        public Nullable<double> VL_PREMIO_TOTAL { get; set; }
        public Nullable<double> VL_IS_TOTAL { get; set; }
        public Nullable<int> QTD_PROPOSTAS { get; set; }
        public Nullable<int> QTD_COTACOES { get; set; }
        public Nullable<int> QTD_EMISSOES { get; set; }
        public Nullable<int> QTD_ITENS { get; set; }
        public string DS_ATRIBUTO_COMPLEMENTAR1 { get; set; }
        public string DS_ATRIBUTO_COMPLEMENTAR2 { get; set; }
        public Nullable<System.DateTime> DS_ATRIBUTO_COMPLEMENTAR3 { get; set; }
        public string DS_ATRIBUTO_COMPLEMENTAR4 { get; set; }
        public string DS_ATRIBUTO_COMPLEMENTAR5 { get; set; }
        public string DS_COTACAO_ATRIBUTO_COMPLEMENTAR3 { get; set; }
        public string ID_CHAVE { get; set; }
        public Nullable<System.DateTime> DT_INICIO_VIGENCIA { get; set; }
        public Nullable<System.DateTime> DT_FIM_VIGENCIA { get; set; }
        public Nullable<short> CD_OCUPACAO { get; set; }
        public string DS_OCUPACAO { get; set; }
        public string CD_ENQUADRAMENTO { get; set; }
        public string DS_OCUPACAO_COMPLETA { get; set; }
        public Nullable<byte> NR_CLASSE_INCENDIO { get; set; }
        public Nullable<byte> NR_CLASSE_ROUBO { get; set; }
        public string DS_PONTOS_ATENCAO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    }
}
