//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_FT_SUN
    {
        public string SUN_CTA_CNB { get; set; }
        public string SUN_DTA_CPT { get; set; }
        public string SUN_DTA_MOV { get; set; }
        public Nullable<decimal> SUN_VALOR { get; set; }
        public string SUN_NATUREZA { get; set; }
        public string SUN_TP_LNC { get; set; }
        public string SUN_FONTE_LNC { get; set; }
        public string SUN_REFERENCIA { get; set; }
        public string SUN_DESC_EVT { get; set; }
        public string SUN_CODE1 { get; set; }
        public string SUN_CODE2 { get; set; }
        public string SUN_CODE3 { get; set; }
        public string SUN_CODE4 { get; set; }
        public string SUN_CODE5 { get; set; }
        public string SUN_CODE6 { get; set; }
        public string SUN_CODE7 { get; set; }
        public string SUN_CODE8 { get; set; }
        public string SUN_CODE9 { get; set; }
        public string SUN_CODE10 { get; set; }
        public string COD_STM { get; set; }
        public int COD_EVT { get; set; }
        public string COD_OBJ_CTZ { get; set; }
        public int DAT_CPT { get; set; }
        public Nullable<int> COD_RMO { get; set; }
        public Nullable<int> COD_CIA_SGD { get; set; }
        public string FLG_PMN { get; set; }
        public Nullable<System.DateTime> DAT_SUN { get; set; }
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public string NUM_AVS_SGO { get; set; }
        public Nullable<int> NUM_PRL { get; set; }
        public string NUM_SOLIC_INSP { get; set; }
        public string NUM_PROP { get; set; }
        public int COD_CRT { get; set; }
        public string CD_ORIGEM { get; set; }
        public string NUM_SIN_MS10 { get; set; }
        public string ID_MOVTOPAGTOSINISTRO { get; set; }
        public string NR_LANCAMENTO { get; set; }
        public string SUN_CODE11 { get; set; }
        public string SUN_CODE12 { get; set; }
        public string SUN_CODE13 { get; set; }
        public string SUN_CODE14 { get; set; }
        public string SUN_CODE15 { get; set; }
        public string SUN_CODE16 { get; set; }
        public string SUN_CODE17 { get; set; }
    }
}
