//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_TITULOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ODS_TITULOS()
        {
            this.TB_ODS_OCORRENCIAS = new HashSet<TB_ODS_OCORRENCIAS>();
            this.TB_ODS_TITULOS_RAMO_ITEM_COBERTURA = new HashSet<TB_ODS_TITULOS_RAMO_ITEM_COBERTURA>();
        }
    
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public string CD_PARCELA { get; set; }
        public string CD_SEG { get; set; }
        public string CD_STM { get; set; }
        public Nullable<decimal> VL_PRE_LQD { get; set; }
        public Nullable<decimal> VL_ADC_FRC { get; set; }
        public Nullable<decimal> VL_CST { get; set; }
        public Nullable<decimal> VL_IOF { get; set; }
        public Nullable<decimal> VL_PRE_TOT { get; set; }
        public Nullable<decimal> TP_STU_TIT { get; set; }
        public Nullable<decimal> VL_COB_VST { get; set; }
        public Nullable<decimal> VL_MTA { get; set; }
        public Nullable<decimal> VL_JRO { get; set; }
        public Nullable<decimal> VL_DSO { get; set; }
        public Nullable<decimal> VL_PRE_DVI { get; set; }
        public string TP_ANTECIPACAO { get; set; }
        public string CD_RAMO { get; set; }
        public Nullable<System.DateTime> DT_VENCIMENTO { get; set; }
        public string CD_ORIGEM { get; set; }
        public string TP_ENDOSSO { get; set; }
        public string COD_CTR { get; set; }
        public Nullable<System.DateTime> DT_PRM_VENC { get; set; }
        public Nullable<System.DateTime> DT_SEG_VENC { get; set; }
        public Nullable<System.DateTime> DT_FIM_VGC_ANT { get; set; }
        public Nullable<System.DateTime> DT_STU_TIT { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public decimal VL_CUSTO_AQUISICAO { get; set; }
    
        public virtual TB_ODS_DETALHE_PARCELA TB_ODS_DETALHE_PARCELA { get; set; }
        public virtual TB_ODS_EMISSAO TB_ODS_EMISSAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_OCORRENCIAS> TB_ODS_OCORRENCIAS { get; set; }
        public virtual TB_ODS_RAMO TB_ODS_RAMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ODS_TITULOS_RAMO_ITEM_COBERTURA> TB_ODS_TITULOS_RAMO_ITEM_COBERTURA { get; set; }
    }
}
