//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_CREDITOS_ANTECIPADOS_HISTORICO
    {
        public int NR_SEQUENCIA { get; set; }
        public string CD_CIA { get; set; }
        public string CD_CONTRATO { get; set; }
        public int CD_EMISSAO { get; set; }
        public string CD_NOSSO_NUMERO { get; set; }
        public string CD_RAMO { get; set; }
        public string CD_PROPOSTA { get; set; }
        public System.DateTime DT_PROPOSTA { get; set; }
        public string CD_PRODUTO { get; set; }
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public Nullable<int> CD_PARCELA { get; set; }
        public Nullable<System.DateTime> DT_PAGAMENTO { get; set; }
        public Nullable<System.DateTime> DT_VENCIMENTO { get; set; }
        public Nullable<System.DateTime> DT_MOVIMENTO { get; set; }
        public string CD_AGENTE_COBRADOR { get; set; }
        public string CD_AGENCIA { get; set; }
        public string NR_CONTACORRENTE { get; set; }
        public string CD_MOEDA { get; set; }
        public string CD_BOLETO { get; set; }
        public Nullable<decimal> VL_PREMIO_LIQ { get; set; }
        public Nullable<decimal> VL_ADICIONAL_FRAC { get; set; }
        public Nullable<decimal> VL_IOF { get; set; }
        public Nullable<decimal> VL_CUSTO_APOLIC { get; set; }
        public Nullable<decimal> VL_COMISSAO { get; set; }
        public Nullable<decimal> VL_COMISSAO_APOLIC { get; set; }
        public string CD_SISTEMA { get; set; }
        public int CD_EVENTO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public Nullable<System.DateTime> DT_EVO_DM { get; set; }
        public string CD_ORIGEM { get; set; }
        public Nullable<long> ID_AVISO_CREDITO { get; set; }
    }
}
