//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_CONTA_KVW
    {
        public int CD_BATIMENTO { get; set; }
        public string NR_CONTA { get; set; }
        public string CD_SIST_OBJ_CONTABIL_ANALITICO { get; set; }
        public bool TP_SINAL { get; set; }
    }
}
