//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_JUDICIAL
    {
        public string NR_PROCESSO { get; set; }
        public string CD_SINISTRO { get; set; }
        public int TP_RELATORIO { get; set; }
        public System.DateTime DT_JURIDICO { get; set; }
        public string NM_SEGURADO { get; set; }
        public string NM_AUTOR { get; set; }
        public string NR_CPF_CNPJ { get; set; }
        public decimal VL_IS { get; set; }
        public decimal VL_MAX { get; set; }
        public decimal VL_SEG { get; set; }
        public int TP_CLASSE_ESTIMATIVA { get; set; }
        public int TP_OPERACAO { get; set; }
        public string UF_REC { get; set; }
        public decimal VL_PROVCONT { get; set; }
        public System.DateTime DT_CARGA { get; set; }
        public Nullable<System.DateTime> DT_PROCESSAMENTO { get; set; }
        public string NM_PLANILHA { get; set; }
    }
}
