//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_EVENTO
    {
        public int ID_EVENTO { get; set; }
        public int ID_SISTEMA { get; set; }
        public int CD_EVENTO { get; set; }
        public string DS_EVENTO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    
        public virtual TB_ODS_SISTEMA TB_ODS_SISTEMA { get; set; }
    }
}
