//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_VEICULO_COTACAO
    {
        public string CD_COTACAO { get; set; }
        public System.DateTime DT_COTACAO { get; set; }
        public int CD_ITEM { get; set; }
        public string CD_VEICULO { get; set; }
        public string DS_VEICULO { get; set; }
        public string CD_VEICULO_SUSEP { get; set; }
        public string CD_GRUPO_VEICULO { get; set; }
        public string DS_GRUPO_VEICULO { get; set; }
        public Nullable<int> CD_CONFIGURACAO { get; set; }
        public string DS_CONFIGURACAO { get; set; }
        public string CD_CATEGORIA { get; set; }
        public string DS_CATEGORIA { get; set; }
        public string CD_MARCA { get; set; }
        public string DS_MARCA { get; set; }
        public string DS_ANO_MODELO { get; set; }
    }
}
