//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_AJUSTES_EST
    {
        public string CD_AVS_SGO { get; set; }
        public string CD_ORIGEM { get; set; }
        public Nullable<System.DateTime> DT_AVISO { get; set; }
        public Nullable<System.DateTime> DT_AVISO_2 { get; set; }
        public Nullable<System.DateTime> DT_OCORR { get; set; }
        public Nullable<System.DateTime> DT_INI_VIG { get; set; }
        public Nullable<System.DateTime> DT_FIN_VIG { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
    }
}
