//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_REVENDA_COTACAO
    {
        public string CD_COTACAO { get; set; }
        public System.DateTime DT_COTACAO { get; set; }
        public int CD_ITEM { get; set; }
        public string TP_REGISTRO { get; set; }
        public string CD_REVENDA { get; set; }
        public string NM_REVENDA { get; set; }
        public string CD_AGRUPAMENTO { get; set; }
        public string NR_CPF_CNPJ { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
    }
}
