//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanilhaResseguro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ODS_TITULOS_RAMO_ITEM_COBERTURA
    {
        public string CD_APOLICE { get; set; }
        public string CD_ENDOSSO { get; set; }
        public string CD_PARCELA { get; set; }
        public string CD_RAMO { get; set; }
        public int CD_ITEM { get; set; }
        public string CD_COB { get; set; }
        public string CD_SEG { get; set; }
        public string CD_STM { get; set; }
        public Nullable<decimal> VL_PRE_LQD { get; set; }
        public Nullable<decimal> VL_ADC_FRC { get; set; }
        public Nullable<decimal> VL_CST { get; set; }
        public Nullable<decimal> VL_IOF { get; set; }
        public Nullable<decimal> VL_PRE_TOT { get; set; }
        public Nullable<decimal> VL_ISG { get; set; }
        public Nullable<decimal> VL_CMS { get; set; }
        public Nullable<decimal> VL_PRE_LQD_ASS { get; set; }
        public Nullable<decimal> VL_ADC_FRQ_ASS { get; set; }
        public Nullable<decimal> VL_IOF_ASS { get; set; }
        public Nullable<decimal> VL_CST_ASS { get; set; }
        public Nullable<decimal> CD_MOEDA { get; set; }
        public string CD_ORIGEM { get; set; }
        public string TP_ENDOSSO { get; set; }
        public Nullable<decimal> VL_CMS_CUSTO { get; set; }
        public Nullable<System.DateTime> DT_CARGA { get; set; }
        public string CD_CTR_RESSEGURO { get; set; }
        public decimal VL_CUSTO_AQUISICAO { get; set; }
    
        public virtual TB_ODS_TITULOS TB_ODS_TITULOS { get; set; }
    }
}
